#!/usr/bin/env python3
"""Peak State coordination CLI and Claude Code hook handler.

Lanes write every coordination record (decisions, status, messages, session
claims, events) through this tool, never by hand, so each record matches its
contract in schemas/coord/ and the generated spec (spec/, coord/trace/) can be
rebuilt byte for byte from the repository. Standard library only, so the hooks
run in any container without an install step.

Agents read across lanes without merging: every lane pushes to its own
branch, and `board`, `inbox`, `show`, `why` and `context` read the coord/
records of every remote branch straight out of git.

Protocol: coord/README.md. Agent rules: CLAUDE.md.
"""

from __future__ import annotations

import argparse
import fnmatch
import hashlib
import json
import os
import re
import secrets
import subprocess
import sys
import time
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
COORD = ROOT / "coord"
SCHEMAS = ROOT / "schemas" / "coord"
DECISION_ID_RE = re.compile(r"^D-([a-z][a-z0-9-]{1,23})-(\d{3})$")
DECISION_PATH_RE = re.compile(r"^coord/decisions/([^/]+)/([^/]+)\.json$")
GENERATED_NOTE = "Generated by `python3 tools/coord.py build` from coord/lanes.json and coord/decisions/. Do not edit by hand."
FETCH_MAX_AGE = 90  # seconds between automatic fetches triggered by hooks
STATUS_STALE_MINUTES = 45
MUTABLE_DECISION_FIELDS = {"status", "acceptedAt", "acceptedBy"}
STATUS_RANK = {"proposed": 0, "accepted": 1, "rejected": 1}
SPECIAL_RECIPIENTS = ("all", "human")


class CoordError(Exception):
    """A problem the person or agent running the command can fix."""


# ---------------------------------------------------------------------------
# Small helpers


def now_iso() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def parse_iso(value):
    if not isinstance(value, str) or "T" not in value:
        return None
    try:
        dt = datetime.fromisoformat(value.replace("Z", "+00:00"))
    except ValueError:
        return None
    return dt if dt.tzinfo else dt.replace(tzinfo=timezone.utc)


def ago(value) -> str:
    dt = parse_iso(value)
    if not dt:
        return "never"
    secs = max(0, int((datetime.now(timezone.utc) - dt).total_seconds()))
    if secs < 60:
        return f"{secs}s ago"
    if secs < 3600:
        return f"{secs // 60}m ago"
    if secs < 86400:
        return f"{secs // 3600}h ago"
    return f"{secs // 86400}d ago"


def read_json(path: Path):
    with open(path, encoding="utf-8") as fh:
        return json.load(fh)


def dumps(obj) -> str:
    return json.dumps(obj, indent=2, ensure_ascii=False) + "\n"


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def sha256_file(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def rel(path: Path) -> str:
    return path.relative_to(ROOT).as_posix()


def git(*args, check=True, timeout=60) -> str:
    try:
        result = subprocess.run(
            ["git", "-C", str(ROOT), *args], capture_output=True, text=True, timeout=timeout
        )
    except subprocess.TimeoutExpired as exc:
        raise CoordError(f"git {args[0]} timed out") from exc
    if check and result.returncode != 0:
        raise CoordError(f"git {' '.join(args)}: {(result.stderr or result.stdout).strip()}")
    return result.stdout


def git_ok(*args, timeout=60):
    try:
        return git(*args, timeout=timeout)
    except CoordError:
        return None


def current_branch():
    branch = (git_ok("rev-parse", "--abbrev-ref", "HEAD") or "").strip()
    return None if branch in ("", "HEAD") else branch


def head_sha():
    return (git_ok("rev-parse", "HEAD") or "").strip() or None


# ---------------------------------------------------------------------------
# Local, per-clone state (inside .git, never committed)


def state_file() -> Path:
    git_dir = Path((git_ok("rev-parse", "--git-dir") or ".git").strip())
    return (git_dir if git_dir.is_absolute() else ROOT / git_dir) / "peak-coord-state.json"


def load_state() -> dict:
    try:
        return read_json(state_file())
    except (OSError, ValueError):
        return {}


def save_state(state: dict) -> None:
    write_text(state_file(), dumps(state))


def update_state(**changes) -> dict:
    state = load_state()
    state.update(changes)
    save_state(state)
    return state


# ---------------------------------------------------------------------------
# Identity


def session_ref() -> dict:
    """The session writing a record. Cloud sessions carry a reopenable URL."""
    remote = os.environ.get("CLAUDE_CODE_REMOTE_SESSION_ID", "").strip()
    if remote:
        tail = remote.split("_", 1)[1] if "_" in remote else remote
        return {
            "id": f"session_{tail}",
            "url": f"https://claude.ai/code/session_{tail}",
            "branch": current_branch(),
        }
    sid = (
        os.environ.get("PEAK_SESSION_ID")
        or os.environ.get("CLAUDE_CODE_SESSION_ID")
        or f"local-{os.environ.get('USER', 'human')}"
    )
    return {"id": sid, "url": None, "branch": current_branch()}


def safe_name(value: str) -> str:
    return re.sub(r"[^A-Za-z0-9_-]", "-", value)[:80]


# ---------------------------------------------------------------------------
# Lanes and ownership


def load_lanes() -> dict:
    path = COORD / "lanes.json"
    if not path.exists():
        raise CoordError("coord/lanes.json is missing")
    return read_json(path)


def lane_map(cfg: dict) -> dict:
    return {lane["id"]: lane for lane in cfg["lanes"]}


def path_matches(path: str, pattern: str) -> bool:
    if pattern.endswith("/"):
        return path.startswith(pattern)
    if any(ch in pattern for ch in "*?["):
        return fnmatch.fnmatchcase(path, pattern)
    return path == pattern


def owner_of(path: str, cfg: dict):
    """The lane owning a path: the longest matching `owns` entry wins."""
    best, best_len = None, -1
    for lane in cfg["lanes"]:
        for pattern in lane["owns"]:
            if path_matches(path, pattern) and len(pattern) > best_len:
                best, best_len = lane["id"], len(pattern)
    return best


def is_generated(path: str, cfg: dict) -> bool:
    return any(path.startswith(prefix) for prefix in cfg.get("generated", []))


def my_lane():
    env = os.environ.get("PEAK_LANE", "").strip()
    if env:
        return env
    state = load_state()
    if state.get("lane"):
        return state["lane"]
    # A resumed session in a fresh container finds its lane in the registry.
    sid = session_ref()["id"]
    for path in sorted((COORD / "sessions").glob("*.json")):
        try:
            record = read_json(path)
        except (OSError, ValueError):
            continue
        if record.get("sessionId") == sid:
            return record.get("lane")
    return None


def require_lane(cfg: dict) -> str:
    lane = my_lane()
    if not lane:
        raise CoordError(
            "No lane claimed. Run: python3 tools/coord.py claim <lane> --purpose '<one line>'. "
            f"Lanes: {', '.join(lane_map(cfg))}"
        )
    if lane not in lane_map(cfg):
        raise CoordError(f"Claimed lane '{lane}' is not in coord/lanes.json")
    return lane


def repo_files() -> list:
    out = git("ls-files", "-z", "--cached", "--others", "--exclude-standard")
    return sorted({f for f in out.split("\0") if f and (ROOT / f).is_file()})


# ---------------------------------------------------------------------------
# A small JSON Schema validator: the subset schemas/coord/ uses.

_SCHEMA_CACHE: dict = {}


def load_schema(name: str) -> dict:
    if name not in _SCHEMA_CACHE:
        _SCHEMA_CACHE[name] = read_json(SCHEMAS / f"{name}.schema.json")
    return _SCHEMA_CACHE[name]


def _type_ok(value, kind: str) -> bool:
    if kind == "object":
        return isinstance(value, dict)
    if kind == "array":
        return isinstance(value, list)
    if kind == "string":
        return isinstance(value, str)
    if kind == "integer":
        return isinstance(value, int) and not isinstance(value, bool)
    if kind == "number":
        return isinstance(value, (int, float)) and not isinstance(value, bool)
    if kind == "boolean":
        return isinstance(value, bool)
    if kind == "null":
        return value is None
    return False


def schema_errors(value, schema: dict, root=None, where="$") -> list:
    root = root or schema
    if "$ref" in schema:
        ref = schema["$ref"]
        if not ref.startswith("#/$defs/"):
            return [f"{where}: unsupported $ref {ref}"]
        return schema_errors(value, root["$defs"][ref[len("#/$defs/"):]], root, where)
    errors = []
    if "anyOf" in schema and all(schema_errors(value, sub, root, where) for sub in schema["anyOf"]):
        errors.append(f"{where}: matches none of the allowed shapes")
    if "const" in schema and value != schema["const"]:
        errors.append(f"{where}: must be {schema['const']!r}")
    if "enum" in schema and value not in schema["enum"]:
        errors.append(f"{where}: must be one of {', '.join(map(str, schema['enum']))}")
    if "type" in schema:
        kinds = schema["type"] if isinstance(schema["type"], list) else [schema["type"]]
        if not any(_type_ok(value, kind) for kind in kinds):
            return errors + [f"{where}: expected {' or '.join(kinds)}"]
    if isinstance(value, str):
        if len(value) < schema.get("minLength", 0):
            errors.append(f"{where}: must not be empty" if schema.get("minLength") == 1 else f"{where}: too short")
        if "maxLength" in schema and len(value) > schema["maxLength"]:
            errors.append(f"{where}: longer than {schema['maxLength']} characters")
        if "pattern" in schema and not re.search(schema["pattern"], value):
            errors.append(f"{where}: does not match {schema['pattern']}")
        if schema.get("format") == "date-time" and not parse_iso(value):
            errors.append(f"{where}: not an ISO 8601 date-time")
    if _type_ok(value, "number"):
        if "minimum" in schema and value < schema["minimum"]:
            errors.append(f"{where}: below {schema['minimum']}")
        if "maximum" in schema and value > schema["maximum"]:
            errors.append(f"{where}: above {schema['maximum']}")
    if isinstance(value, dict):
        for key in schema.get("required", []):
            if key not in value:
                errors.append(f"{where}: missing '{key}'")
        props = schema.get("properties", {})
        extra = schema.get("additionalProperties", True)
        for key, item in value.items():
            if key in props:
                errors += schema_errors(item, props[key], root, f"{where}.{key}")
            elif extra is False:
                errors.append(f"{where}: unexpected field '{key}'")
            elif isinstance(extra, dict):
                errors += schema_errors(item, extra, root, f"{where}.{key}")
    if isinstance(value, list):
        if len(value) < schema.get("minItems", 0):
            errors.append(f"{where}: needs at least {schema['minItems']} item(s)")
        if schema.get("uniqueItems") and len({json.dumps(v, sort_keys=True) for v in value}) != len(value):
            errors.append(f"{where}: items must be unique")
        if "items" in schema:
            for index, item in enumerate(value):
                errors += schema_errors(item, schema["items"], root, f"{where}[{index}]")
    return errors


# ---------------------------------------------------------------------------
# Decisions


def local_decisions() -> dict:
    decisions = {}
    for path in sorted((COORD / "decisions").glob("*/D-*.json")):
        try:
            record = read_json(path)
        except (OSError, ValueError):
            continue
        decisions[record.get("id", path.stem)] = record
    return decisions


def effective_status(decisions: dict) -> dict:
    """Stored status, except a decision named in a live `supersedes` is superseded."""
    status = {did: rec.get("status", "proposed") for did, rec in decisions.items()}
    for rec in decisions.values():
        if rec.get("status") == "rejected":
            continue
        for old in rec.get("supersedes", []):
            if old in status and status[old] != "rejected":
                status[old] = "superseded"
    return status


def superseded_by(decisions: dict) -> dict:
    out = defaultdict(list)
    for did, rec in sorted(decisions.items()):
        if rec.get("status") != "rejected":
            for old in rec.get("supersedes", []):
                out[old].append(did)
    return out


def covering(path: str, decisions: dict, eff: dict) -> list:
    return sorted(
        did
        for did, rec in decisions.items()
        if eff.get(did) != "rejected" and any(path_matches(path, p) for p in rec.get("produces", []))
    )


def next_decision_id(lane: str, known_ids) -> str:
    numbers = []
    for did in known_ids:
        match = DECISION_ID_RE.match(did)
        if match and match.group(1) == lane:
            numbers.append(int(match.group(2)))
    return f"D-{lane}-{(max(numbers) + 1 if numbers else 1):03d}"


# ---------------------------------------------------------------------------
# Writers


def log_event(lane: str, kind: str, ref: str, summary: str) -> None:
    event = {"ts": now_iso(), "lane": lane, "kind": kind, "ref": ref, "summary": summary[:240], "session": session_ref()["id"]}
    path = COORD / "events" / f"{lane}.jsonl"
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "a", encoding="utf-8") as fh:
        fh.write(json.dumps(event, ensure_ascii=False) + "\n")


def touch_session(lane: str, purpose=None) -> Path:
    ref = session_ref()
    path = COORD / "sessions" / f"{lane}--{safe_name(ref['id'])}.json"
    previous = {}
    if path.exists():
        try:
            previous = read_json(path)
        except (OSError, ValueError):
            previous = {}
    stamp = now_iso()
    record = {
        "schemaVersion": 1,
        "sessionId": ref["id"],
        "url": ref["url"],
        "lane": lane,
        "branch": ref["branch"],
        "purpose": purpose if purpose is not None else previous.get("purpose", ""),
        "startedAt": previous.get("startedAt", stamp),
        "lastSeenAt": stamp,
    }
    write_text(path, dumps(record))
    return path


def build_outputs(cfg=None, decisions=None, files=None) -> dict:
    """Every generated file and its exact content. Deterministic: no clocks."""
    cfg = cfg or load_lanes()
    decisions = local_decisions() if decisions is None else decisions
    files = repo_files() if files is None else files
    eff = effective_status(decisions)
    outputs = {}
    for lane in cfg["lanes"]:
        lid = lane["id"]
        rows = []
        for path in files:
            if is_generated(path, cfg) or owner_of(path, cfg) != lid:
                continue
            rows.append({"path": path, "sha256": sha256_file(ROOT / path), "decisions": covering(path, decisions, eff)})
        outputs[f"coord/trace/{lid}.json"] = dumps({"schemaVersion": 1, "lane": lid, "files": rows})
        outputs[f"spec/{lid}.md"] = render_lane_spec(lane, cfg, decisions, eff, rows)
    outputs["spec/README.md"] = render_spec_index(cfg)
    return outputs


def write_build(cfg=None) -> list:
    """Write generated files; return the paths that changed."""
    cfg = cfg or load_lanes()
    outputs = build_outputs(cfg)
    changed = []
    for path, text in outputs.items():
        target = ROOT / path
        if not target.exists() or target.read_text(encoding="utf-8") != text:
            write_text(target, text)
            changed.append(path)
    for folder, suffix in (("coord/trace", ".json"), ("spec", ".md")):
        for stale in sorted((ROOT / folder).glob(f"*{suffix}")):
            if rel(stale) not in outputs:
                stale.unlink()
                changed.append(rel(stale) + " (removed)")
    return changed


# ---------------------------------------------------------------------------
# Spec rendering


def _md_session(session: dict) -> str:
    if not session:
        return "session unknown"
    if session.get("url"):
        return f"[session]({session['url']})"
    return f"session `{session.get('id')}`"


def _md_decision(rec: dict, eff: dict, sup_by: dict) -> list:
    did = rec["id"]
    meta = [f"`{eff.get(did, rec.get('status'))}`", rec.get("type", ""), rec.get("createdAt", "")[:10], _md_session(rec.get("session"))]
    if rec.get("session", {}).get("branch"):
        meta.append(f"branch `{rec['session']['branch']}`")
    if rec.get("acceptedBy"):
        meta.append(f"accepted by {rec['acceptedBy']}")
    lines = [f"### {did} · {rec.get('title', '')}", "", " · ".join(m for m in meta if m), "", f"**Decision.** {rec.get('decision', '').strip()}", "", f"**Context.** {rec.get('context', '').strip()}", ""]
    if rec.get("alternatives"):
        lines += ["**Alternatives considered.**", ""] + [f"- {alt}" for alt in rec["alternatives"]] + [""]
    if rec.get("consequences"):
        lines += [f"**Consequences.** {rec['consequences'].strip()}", ""]
    links = []
    if rec.get("produces"):
        links.append("**Produces:** " + ", ".join(f"`{p}`" for p in rec["produces"]))
    if rec.get("dependsOn"):
        links.append("**Depends on:** " + ", ".join(rec["dependsOn"]))
    if rec.get("supersedes"):
        links.append("**Supersedes:** " + ", ".join(rec["supersedes"]))
    if sup_by.get(did):
        links.append("**Superseded by:** " + ", ".join(sup_by[did]))
    if links:
        lines += ["  \n".join(links), ""]
    return lines


def render_lane_spec(lane: dict, cfg: dict, decisions: dict, eff: dict, rows: list) -> str:
    lid = lane["id"]
    sup_by = superseded_by(decisions)
    own = [decisions[d] for d in sorted(decisions) if decisions[d].get("lane") == lid]
    in_force = [r for r in own if eff[r["id"]] == "accepted"]
    proposed = [r for r in own if eff[r["id"]] == "proposed"]
    retired = [r for r in own if eff[r["id"]] in ("superseded", "rejected")]
    foreign = sorted({d for row in rows for d in row["decisions"] if decisions.get(d, {}).get("lane") != lid})
    lines = [
        f"# {lane['name']} (`{lid}`)",
        "",
        f"> {GENERATED_NOTE} The live view across every branch is the dashboard.",
        "",
        lane["mission"],
        "",
        "**Owns:** " + ", ".join(f"`{p}`" for p in lane["owns"]) + "  ",
        "**Depends on:** " + (", ".join(f"`{d}`" for d in lane["dependsOn"]) or "nothing") + "  ",
        f"**Brief:** [docs/hackathon/lanes/{lid}.md](../docs/hackathon/lanes/{lid}.md)",
        "",
        "## Deliverables",
        "",
    ]
    lines += [f"- {item}" for item in lane["deliverables"]] + [""]
    lines += ["## Decisions in force", ""]
    if in_force:
        for rec in in_force:
            lines += _md_decision(rec, eff, sup_by)
    else:
        lines += ["None yet.", ""]
    lines += ["## Proposed, awaiting acceptance", ""]
    if proposed:
        for rec in proposed:
            lines += _md_decision(rec, eff, sup_by)
    else:
        lines += ["None.", ""]
    lines += ["## Superseded and rejected", ""]
    if retired:
        for rec in retired:
            note = f" (superseded by {', '.join(sup_by[rec['id']])})" if sup_by.get(rec["id"]) else ""
            lines.append(f"- {rec['id']} · {rec.get('title', '')} · `{eff[rec['id']]}`{note}")
        lines.append("")
    else:
        lines += ["None.", ""]
    if foreign:
        lines += ["## Decisions from other lanes that cover files here", ""]
        lines += [f"- {d} · {decisions[d].get('title', '')} (`{decisions[d].get('lane')}`)" for d in foreign] + [""]
    lines += ["## Produced artifacts", "", "Every file this lane owns, the first 12 hex digits of its SHA-256 at build time, and the decisions that cover it.", ""]
    if rows:
        lines += ["| File | sha256 | Decisions |", "|---|---|---|"]
        for row in rows:
            lines.append(f"| `{row['path']}` | `{row['sha256'][:12]}` | {', '.join(row['decisions']) or '**uncovered**'} |")
        lines.append("")
    else:
        lines += ["No files yet.", ""]
    return "\n".join(lines).rstrip() + "\n"


def render_spec_index(cfg: dict) -> str:
    project = cfg["project"]
    lines = [
        f"# {project['name']} spec",
        "",
        f"> {GENERATED_NOTE}",
        "",
        "The spec is the decision log rendered per lane. Each lane file lists the decisions in force, the proposals waiting on someone, and every file the lane owns with the hash it had when the spec was built and the decisions that cover it. A file no decision covers fails CI.",
        "",
        "Each branch carries the spec for its own state. The dashboard merges every branch into one live view"
        + (f": {project['dashboardUrl']}" if project.get("dashboardUrl") else "."),
        "",
        "| Lane | Mission | Spec |",
        "|---|---|---|",
    ]
    for lane in cfg["lanes"]:
        lines.append(f"| `{lane['id']}` {lane['name']} | {lane['mission']} | [{lane['id']}.md]({lane['id']}.md) |")
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Reading every branch


def fetch(force=False, max_age=FETCH_MAX_AGE) -> bool:
    state = load_state()
    if not force and time.time() - state.get("lastFetch", 0) < max_age:
        return True
    ok = git_ok("fetch", "--quiet", "--prune", "origin", "+refs/heads/*:refs/remotes/origin/*", timeout=30) is not None
    update_state(lastFetch=time.time(), lastFetchOk=ok)
    return ok


def remote_refs() -> list:
    out = git_ok(
        "for-each-ref",
        "--sort=-committerdate",
        "--format=%(refname)%09%(objectname)%09%(committerdate:iso-strict)%09%(subject)",
        "refs/remotes/origin",
    ) or ""
    refs = []
    for line in out.splitlines():
        parts = line.split("\t", 3)
        if len(parts) < 4 or parts[0].endswith("/HEAD"):
            continue
        refs.append({"name": parts[0][len("refs/remotes/origin/"):], "ref": parts[0], "sha": parts[1], "committedAt": parts[2], "subject": parts[3]})
    return refs


def tree_entries(ref: str, prefix="coord/") -> list:
    out = git_ok("ls-tree", "-r", "-z", ref, "--", prefix) or ""
    entries = []
    for item in out.split("\0"):
        if not item or "\t" not in item:
            continue
        meta, path = item.split("\t", 1)
        parts = meta.split()
        if len(parts) == 3 and parts[1] == "blob":
            entries.append((path, parts[2]))
    return entries


def read_blobs(shas) -> dict:
    shas = sorted(set(shas))
    if not shas:
        return {}
    result = subprocess.run(
        ["git", "-C", str(ROOT), "cat-file", "--batch"],
        input=("\n".join(shas) + "\n").encode(),
        capture_output=True,
        timeout=60,
    )
    data, out, i = result.stdout, {}, 0
    while i < len(data):
        newline = data.index(b"\n", i)
        header = data[i:newline].decode().split()
        i = newline + 1
        if len(header) < 3:
            continue
        size = int(header[2])
        out[header[0]] = data[i : i + size].decode("utf-8", "replace")
        i += size + 1
    return out


def collect(fetch_first=False, include_worktree=True) -> dict:
    """Merge coord/ records from the working tree and every remote branch."""
    fetched = fetch() if fetch_first else None
    refs = remote_refs()
    sources = []
    if include_worktree and COORD.is_dir():
        files = {rel(p): p.read_text(encoding="utf-8", errors="replace") for p in sorted(COORD.rglob("*")) if p.is_file()}
        sources.append(("worktree", files))
    entries = {r["name"]: tree_entries(r["ref"]) for r in refs}
    blobs = read_blobs(sha for es in entries.values() for _, sha in es)
    for r in refs:
        sources.append((r["name"], {path: blobs.get(sha, "") for path, sha in entries[r["name"]]}))

    view = {
        "decisions": {}, "status": {}, "sessions": {}, "messages": {}, "events": {}, "trace": defaultdict(dict),
        "lanes": None, "branches": refs, "parseErrors": [], "fetched": fetched,
    }
    lanes_by_source = {}
    for label, files in sources:
        for path, text in files.items():
            if path.endswith(".jsonl") and path.startswith("coord/events/"):
                for line in text.splitlines():
                    line = line.strip()
                    if not line:
                        continue
                    try:
                        event = json.loads(line)
                    except ValueError:
                        continue
                    key = json.dumps(event, sort_keys=True)
                    view["events"].setdefault(key, {**event, "branch": label})
                continue
            if not path.endswith(".json"):
                continue
            try:
                record = json.loads(text)
            except ValueError:
                view["parseErrors"].append(f"{label}:{path}")
                continue
            if path == "coord/lanes.json":
                lanes_by_source[label] = record
            elif DECISION_PATH_RE.match(path):
                _merge_decision(view["decisions"], record, label)
            elif path.startswith("coord/status/"):
                lane = record.get("lane")
                prev = view["status"].get(lane)
                if lane and (not prev or record.get("updatedAt", "") > prev.get("updatedAt", "")):
                    view["status"][lane] = {**record, "branchSeen": label}
            elif path.startswith("coord/sessions/"):
                key = Path(path).name
                prev = view["sessions"].get(key)
                if not prev or record.get("lastSeenAt", "") > prev.get("lastSeenAt", ""):
                    view["sessions"][key] = record
            elif path.startswith("coord/messages/"):
                view["messages"].setdefault(record.get("id", path), {**record, "branchSeen": label})
            elif path.startswith("coord/trace/"):
                view["trace"][record.get("lane")][label] = record
    for preferred in ("worktree", "main"):
        if preferred in lanes_by_source:
            view["lanes"] = lanes_by_source[preferred]
            break
    else:
        view["lanes"] = next(iter(lanes_by_source.values()), None)
    if view["lanes"] is None:
        view["lanes"] = load_lanes()
    return view


def _merge_decision(store: dict, record: dict, label: str) -> None:
    did = record.get("id")
    if not did:
        return
    body = json.dumps({k: v for k, v in record.items() if k not in MUTABLE_DECISION_FIELDS}, sort_keys=True)
    entry = store.get(did)
    if entry is None:
        store[did] = {"record": record, "branches": [label], "bodies": {body}}
        return
    entry["branches"].append(label)
    entry["bodies"].add(body)
    if STATUS_RANK.get(record.get("status"), 0) > STATUS_RANK.get(entry["record"].get("status"), 0):
        entry["record"] = record


def view_decisions(view: dict) -> dict:
    return {did: entry["record"] for did, entry in view["decisions"].items()}


def pick_trace(view: dict, lane: str):
    variants = view["trace"].get(lane, {})
    if not variants:
        return None
    status = view["status"].get(lane)
    for label in ("worktree", (status or {}).get("branchSeen"), (status or {}).get("session", {}).get("branch"), "main"):
        if label and label in variants:
            return variants[label]
    return next(iter(variants.values()))


def latest_sessions(view: dict, lane: str) -> list:
    sessions = [s for s in view["sessions"].values() if s.get("lane") == lane]
    return sorted(sessions, key=lambda s: s.get("lastSeenAt", ""), reverse=True)


def inbox_for(view: dict, lane: str) -> list:
    msgs = [m for m in view["messages"].values() if m.get("to") in (lane, "all") and m.get("from") != lane]
    return sorted(msgs, key=lambda m: m.get("createdAt", ""), reverse=True)


# ---------------------------------------------------------------------------
# Text views


def render_board(view: dict, lane=None, decisions_limit=8) -> str:
    cfg = view["lanes"]
    decisions = view_decisions(view)
    eff = effective_status(decisions)
    lines = ["LANES  (health · progress · last update · summary)"]
    for item in cfg["lanes"]:
        lid = item["id"]
        status = view["status"].get(lid)
        marker = "→" if lid == lane else " "
        if status:
            lines.append(
                f"{marker} {lid:<11} {status.get('health', '?'):<5} {status.get('progress', 0):>3}%  {ago(status.get('updatedAt')):>8}  {status.get('summary', '')[:110]}"
            )
            for blocker in status.get("blockers", [])[:3]:
                lines.append(f"      BLOCKER: {blocker[:120]}")
        else:
            lines.append(f"{marker} {lid:<11} —      no status yet")
        sessions = latest_sessions(view, lid)
        if sessions:
            s = sessions[0]
            lines.append(f"      session {s.get('url') or s.get('sessionId')} · branch {s.get('branch')} · seen {ago(s.get('lastSeenAt'))}")
    recent = sorted(decisions.values(), key=lambda r: r.get("createdAt", ""), reverse=True)[:decisions_limit]
    if recent:
        lines += ["", "RECENT DECISIONS"]
        for rec in recent:
            lines.append(f"  {rec['id']:<18} [{eff.get(rec['id'])}] {rec.get('title', '')[:90]} · {ago(rec.get('createdAt'))}")
    waiting = [r for r in decisions.values() if eff.get(r["id"]) == "proposed"]
    if waiting:
        lines += ["", "PROPOSED, WAITING FOR ACCEPTANCE"]
        for rec in sorted(waiting, key=lambda r: r["id"]):
            lines.append(f"  {rec['id']:<18} {rec.get('title', '')[:100]}")
    conflicts = [did for did, entry in view["decisions"].items() if len(entry["bodies"]) > 1]
    if conflicts:
        lines += ["", "CONFLICTING DECISION IDS (same id, different content on different branches): " + ", ".join(sorted(conflicts))]
    return "\n".join(lines)


def render_message(msg: dict) -> str:
    refs = f" refs {', '.join(msg['refs'])}" if msg.get("refs") else ""
    return f"  {msg['id']} · {msg.get('from')} → {msg.get('to')} · {ago(msg.get('createdAt'))}{refs}\n    {msg.get('subject')}: {msg.get('body', '')[:400]}"


LOOP_TEXT = """THE LOOP (required; hooks block push and stop when it is skipped)
  1 decide  python3 tools/coord.py decide --title "…" --decision "…" --context "…" --produces <paths…> [--status proposed]
  2 build   only inside paths your lane owns; ask another lane: python3 tools/coord.py msg <lane> --subject "…" --body "…"
  3 status  python3 tools/coord.py status --health green --progress 30 --summary "…" --now "…" --next "…"
  4 ship    git add -A && git commit -m "…" && git push -u origin <your branch>   (pre-push check rebuilds spec/ and validates)
  look      coord.py board | inbox | show D-… | why <path> | context <lane>"""


# ---------------------------------------------------------------------------
# Validation


def validate(base=None):
    errors, warnings = [], []
    cfg = load_lanes()
    errors += [f"coord/lanes.json {e}" for e in schema_errors(cfg, load_schema("lanes"))]
    if errors:
        return errors, warnings
    ids = set(lane_map(cfg))
    seen_patterns = {}
    for lane in cfg["lanes"]:
        for pattern in lane["owns"]:
            if pattern in seen_patterns:
                errors.append(f"coord/lanes.json: '{pattern}' is owned by both {seen_patterns[pattern]} and {lane['id']}")
            seen_patterns[pattern] = lane["id"]
        for dep in lane["dependsOn"]:
            if dep not in ids:
                errors.append(f"coord/lanes.json: lane {lane['id']} depends on unknown lane {dep}")

    files = repo_files()
    decisions = {}
    for path in files:
        match = DECISION_PATH_RE.match(path)
        if match:
            try:
                record = read_json(ROOT / path)
            except ValueError as exc:
                errors.append(f"{path}: invalid JSON ({exc})")
                continue
            errors += [f"{path} {e}" for e in schema_errors(record, load_schema("decision"))]
            did, lane = record.get("id", ""), record.get("lane")
            expected = f"coord/decisions/{lane}/{did}.json"
            if path != expected:
                errors.append(f"{path}: must live at {expected}")
            if lane not in ids:
                errors.append(f"{path}: unknown lane '{lane}'")
            id_match = DECISION_ID_RE.match(did)
            if id_match and id_match.group(1) != lane:
                errors.append(f"{path}: id {did} does not belong to lane {lane}")
            if did in decisions:
                errors.append(f"{path}: duplicate decision id {did}")
            decisions[did] = record
        elif path.startswith("coord/decisions/"):
            errors.append(f"{path}: only coord/decisions/<lane>/D-<lane>-NNN.json files belong here")
        elif path.startswith("coord/status/"):
            record = _load_for_validation(path, errors)
            if record is not None:
                errors += [f"{path} {e}" for e in schema_errors(record, load_schema("status"))]
                if path != f"coord/status/{record.get('lane')}.json":
                    errors.append(f"{path}: file name must match its lane")
        elif path.startswith("coord/messages/"):
            record = _load_for_validation(path, errors)
            if record is not None:
                errors += [f"{path} {e}" for e in schema_errors(record, load_schema("message"))]
                if record.get("to") not in ids | set(SPECIAL_RECIPIENTS):
                    errors.append(f"{path}: unknown recipient '{record.get('to')}'")
        elif path.startswith("coord/sessions/"):
            record = _load_for_validation(path, errors)
            if record is not None:
                errors += [f"{path} {e}" for e in schema_errors(record, load_schema("session"))]
        elif path.startswith("coord/events/"):
            for number, line in enumerate((ROOT / path).read_text(encoding="utf-8").splitlines(), 1):
                if not line.strip():
                    continue
                try:
                    event = json.loads(line)
                except ValueError:
                    errors.append(f"{path}:{number}: invalid JSON")
                    continue
                errors += [f"{path}:{number} {e}" for e in schema_errors(event, load_schema("event"))]

    for did, record in sorted(decisions.items()):
        for ref in record.get("dependsOn", []) + record.get("supersedes", []):
            if ref not in decisions:
                warnings.append(f"{did} references {ref}, which is not on this branch (fine if it lives on another lane's branch)")
        for pattern in record.get("produces", []):
            if ".." in pattern.split("/"):
                errors.append(f"{did}: produces entry '{pattern}' leaves the repository")
            elif not any(path_matches(f, pattern) for f in files):
                warnings.append(f"{did}: produces '{pattern}', which does not exist yet")

    eff = effective_status(decisions)
    uncovered = defaultdict(list)
    for path in files:
        if is_generated(path, cfg):
            continue
        owner = owner_of(path, cfg)
        if owner is None:
            errors.append(f"{path}: no lane owns this path. Move it under your lane's paths or ask coord to extend coord/lanes.json")
            continue
        if not covering(path, decisions, eff):
            uncovered[owner].append(path)
    for lane, paths in sorted(uncovered.items()):
        shown = ", ".join(paths[:12]) + (" …" if len(paths) > 12 else "")
        errors.append(
            f"{len(paths)} file(s) owned by lane '{lane}' are not covered by any decision: {shown}. "
            "Log the decision that produced them: python3 tools/coord.py decide … --produces <paths>"
        )

    expected = build_outputs(cfg, decisions, files)
    stale = sorted(p for p, text in expected.items() if not (ROOT / p).exists() or (ROOT / p).read_text(encoding="utf-8") != text)
    stale += sorted(f"{p} (orphan)" for p in files if (p.startswith("coord/trace/") or p.startswith("spec/")) and p not in expected)
    if stale:
        errors.append("Generated spec is out of date: " + ", ".join(stale) + ". Run: python3 tools/coord.py build")

    for ref in ([base] if isinstance(base, str) else list(base or [])):
        errors += [e for e in _immutability_errors(ref) if e not in errors]
    return errors, warnings


def _load_for_validation(path: str, errors: list):
    try:
        return read_json(ROOT / path)
    except ValueError as exc:
        errors.append(f"{path}: invalid JSON ({exc})")
        return None


def _immutability_errors(base: str) -> list:
    """Decisions present at the merge base with `base` may only change status."""
    merge_base = (git_ok("merge-base", "HEAD", base) or "").strip()
    if not merge_base:
        return []
    errors = []
    listing = git_ok("ls-tree", "-r", "--name-only", merge_base, "--", "coord/decisions/") or ""
    for path in listing.splitlines():
        if not DECISION_PATH_RE.match(path):
            continue
        current = ROOT / path
        if not current.exists():
            errors.append(f"{path}: decisions are append-only and this one was deleted. Supersede it instead.")
            continue
        try:
            old = json.loads(git("show", f"{merge_base}:{path}"))
            new = read_json(current)
        except (ValueError, CoordError):
            continue
        strip = lambda record: {k: v for k, v in record.items() if k not in MUTABLE_DECISION_FIELDS}  # noqa: E731
        if strip(old) != strip(new):
            errors.append(f"{path}: decisions are immutable except status. Write a new decision with --supersedes {old.get('id')} instead.")
    return errors


# ---------------------------------------------------------------------------
# Commands


def cmd_claim(args):
    cfg = load_lanes()
    lanes = lane_map(cfg)
    if args.lane not in lanes:
        raise CoordError(f"Unknown lane '{args.lane}'. Lanes: {', '.join(lanes)}")
    view = collect(fetch_first=not args.no_fetch)
    sid = session_ref()["id"]
    others = [s for s in latest_sessions(view, args.lane) if s.get("sessionId") != sid and (parse_iso(s.get("lastSeenAt")) or datetime.min.replace(tzinfo=timezone.utc)).timestamp() > time.time() - 6 * 3600]
    state = load_state()
    state.update({"lane": args.lane, "claimedAt": now_iso()})
    state.setdefault("startHead", head_sha())
    save_state(state)
    path = touch_session(args.lane, args.purpose or "")
    log_event(args.lane, "claim", sid, args.purpose or f"claimed {args.lane}")
    print(f"Claimed lane '{args.lane}' ({lanes[args.lane]['name']}) for {session_ref()['url'] or sid}. Registered in {rel(path)}.")
    print(f"Brief: docs/hackathon/lanes/{args.lane}.md · you own: {', '.join(lanes[args.lane]['owns'])}")
    for other in others:
        print(f"WARNING: session {other.get('url') or other.get('sessionId')} also worked this lane {ago(other.get('lastSeenAt'))} on branch {other.get('branch')}. Coordinate before you both write decisions.")
    expected = f"{cfg['project']['laneBranchPrefix']}{args.lane}"
    branch = current_branch()
    if args.lane != "coord" and branch != expected:
        print(
            f"WARNING: you are on branch '{branch}', not '{expected}'. If your session was told to push to {expected}, "
            f"switch first so your records name the right branch: git checkout -B {expected} && python3 tools/coord.py claim {args.lane}"
        )


def _field(args, fields, name, default=None):
    value = getattr(args, name, None)
    if value not in (None, []):
        return value
    return fields.get(name, default)


def cmd_decide(args):
    cfg = load_lanes()
    lane = args.lane or require_lane(cfg)
    if lane not in lane_map(cfg):
        raise CoordError(f"Unknown lane '{lane}'")
    fields = {}
    if args.json:
        fields = json.load(sys.stdin) if args.json == "-" else read_json(Path(args.json))
    known = set(local_decisions()) | set(collect(include_worktree=False)["decisions"])
    did = next_decision_id(lane, known)
    status = _field(args, fields, "status", "accepted")
    record = {
        "schemaVersion": 1,
        "id": did,
        "lane": lane,
        "title": _field(args, fields, "title"),
        "status": status,
        "type": _field(args, fields, "type", "technical"),
        "context": _field(args, fields, "context"),
        "decision": _field(args, fields, "decision"),
        "alternatives": _field(args, fields, "alternatives", []),
        "consequences": _field(args, fields, "consequences", ""),
        "produces": _field(args, fields, "produces", []),
        "dependsOn": _field(args, fields, "dependsOn", []),
        "supersedes": _field(args, fields, "supersedes", []),
        "author": _field(args, fields, "author", os.environ.get("PEAK_AUTHOR", "claude")),
        "session": session_ref(),
        "createdAt": now_iso(),
    }
    if status == "accepted":
        record["acceptedAt"] = record["createdAt"]
        record["acceptedBy"] = record["author"]
    errors = schema_errors(record, load_schema("decision"))
    if errors:
        raise CoordError("Decision not written:\n  " + "\n  ".join(errors))
    path = COORD / "decisions" / lane / f"{did}.json"
    write_text(path, dumps(record))
    log_event(lane, "decision", did, f"[{status}] {record['title']}")
    touch_session(lane)
    write_build(cfg)
    print(f"{did} [{status}] {record['title']}\n  wrote {rel(path)} and rebuilt spec/{lane}.md")
    if lane != my_lane():
        print(f"  note: recorded in lane '{lane}', which is not your claimed lane")


def cmd_set_decision_status(args, new_status):
    cfg = load_lanes()
    matches = sorted((COORD / "decisions").glob(f"*/{args.id}.json"))
    if not matches:
        view = collect(fetch_first=True, include_worktree=False)
        entry = view["decisions"].get(args.id)
        if entry:
            owner = entry["record"].get("lane")
            raise CoordError(
                f"{args.id} lives on branch(es) {', '.join(entry['branches'])}, not here. Ask its lane: "
                f"python3 tools/coord.py msg {owner} --subject '{new_status} {args.id}' --body '…' --refs {args.id}"
            )
        raise CoordError(f"No decision {args.id}")
    path = matches[0]
    record = read_json(path)
    record["status"] = new_status
    record["acceptedAt"] = now_iso() if new_status == "accepted" else None
    record["acceptedBy"] = args.by or os.environ.get("PEAK_AUTHOR", "claude")
    errors = schema_errors(record, load_schema("decision"))
    if errors:
        raise CoordError("; ".join(errors))
    write_text(path, dumps(record))
    actor_lane = my_lane() or record["lane"]
    log_event(actor_lane, "accept" if new_status == "accepted" else "reject", args.id, f"{new_status} by {record['acceptedBy']}" + (f": {args.note}" if args.note else ""))
    write_build(cfg)
    print(f"{args.id} is now {new_status}")


def cmd_status(args):
    cfg = load_lanes()
    lane = args.lane or require_lane(cfg)
    path = COORD / "status" / f"{lane}.json"
    prev = read_json(path) if path.exists() else {}
    record = {
        "schemaVersion": 1,
        "lane": lane,
        "health": args.health or prev.get("health", "green"),
        "phase": args.phase if args.phase is not None else prev.get("phase", ""),
        "progress": args.progress if args.progress is not None else prev.get("progress", 0),
        "summary": args.summary,
        "now": args.now if args.now is not None else prev.get("now", []),
        "next": args.next if args.next is not None else prev.get("next", []),
        "blockers": [] if args.clear_blockers else (args.blocker if args.blocker is not None else prev.get("blockers", [])),
        "updatedAt": now_iso(),
        "session": session_ref(),
    }
    errors = schema_errors(record, load_schema("status"))
    if errors:
        raise CoordError("Status not written:\n  " + "\n  ".join(errors))
    write_text(path, dumps(record))
    log_event(lane, "status", record["health"], record["summary"])
    touch_session(lane)
    write_build(cfg)
    print(f"Status for {lane}: {record['health']} {record['progress']}% · {record['summary']}")


def cmd_msg(args):
    cfg = load_lanes()
    sender = args.lane or require_lane(cfg)
    lanes = lane_map(cfg)
    if args.to not in lanes and args.to not in SPECIAL_RECIPIENTS:
        raise CoordError(f"Unknown recipient '{args.to}'. Use a lane ({', '.join(lanes)}), all, or human")
    stamp = now_iso()
    mid = f"M-{stamp.replace('-', '').replace(':', '')}-{sender}-{secrets.token_hex(2)}"
    record = {
        "schemaVersion": 1,
        "id": mid,
        "from": sender,
        "to": args.to,
        "subject": args.subject,
        "body": args.body,
        "refs": args.refs or [],
        "replyTo": args.reply_to,
        "createdAt": stamp,
        "session": session_ref(),
    }
    errors = schema_errors(record, load_schema("message"))
    if errors:
        raise CoordError("Message not written:\n  " + "\n  ".join(errors))
    write_text(COORD / "messages" / f"{mid}.json", dumps(record))
    log_event(sender, "message", mid, f"to {args.to}: {args.subject}")
    touch_session(sender)
    print(f"{mid} queued for {args.to}. It reaches them when you push your branch.")


def cmd_borrow(args):
    cfg = load_lanes()
    lane = require_lane(cfg)
    target = args.path.lstrip("./")
    owner = owner_of(target, cfg)
    if owner == lane:
        print(f"{target} is already yours")
        return
    state = load_state()
    borrowed = set(state.get("borrowed", []))
    borrowed.add(target)
    update_state(borrowed=sorted(borrowed))
    if owner:
        args_ns = argparse.Namespace(lane=lane, to=owner, subject=f"editing {target}"[:120], body=args.reason, refs=args.refs or [], reply_to=None)
        cmd_msg(args_ns)
    log_event(lane, "borrow", target, args.reason)
    print(f"{target} unlocked for this clone. Cover it with a decision before you push.")


def cmd_board(args):
    view = collect(fetch_first=not args.no_fetch)
    if args.json:
        print(json.dumps(site_data(view), indent=2, ensure_ascii=False))
        return
    print(render_board(view, my_lane(), decisions_limit=args.limit))


def cmd_inbox(args):
    lane = args.lane or my_lane()
    if not lane:
        raise CoordError("No lane claimed; pass --lane")
    view = collect(fetch_first=not args.no_fetch)
    msgs = inbox_for(view, lane)
    state = load_state()
    seen = set(state.get("seen", []))
    shown = msgs if args.all else [m for m in msgs if m["id"] not in seen]
    if not shown:
        print(f"No {'messages' if args.all else 'new messages'} for {lane}.")
    for msg in shown[: args.limit]:
        print(render_message(msg))
    update_state(seen=sorted(seen | {m["id"] for m in msgs})[-1000:])


def cmd_show(args):
    view = collect(fetch_first=not args.no_fetch)
    decisions = view_decisions(view)
    if args.id not in decisions:
        raise CoordError(f"No decision {args.id} on any branch")
    eff = effective_status(decisions)
    rec = decisions[args.id]
    entry = view["decisions"][args.id]
    session = rec.get("session", {})
    print(f"{rec['id']} · {rec['title']}\n  status {eff[rec['id']]} · type {rec['type']} · lane {rec['lane']} · {rec['createdAt']} · by {rec.get('author')}")
    print(f"  session {session.get('url') or session.get('id')} on branch {session.get('branch')} (reopen it to recover the reasoning)")
    print(f"  seen on: {', '.join(entry['branches'])}" + ("  ⚠ content differs between branches" if len(entry["bodies"]) > 1 else ""))
    print(f"\nDecision: {rec['decision']}\nContext: {rec['context']}")
    if rec.get("alternatives"):
        print("Alternatives: " + "; ".join(rec["alternatives"]))
    if rec.get("consequences"):
        print(f"Consequences: {rec['consequences']}")
    for label, ids in (("Depends on", rec.get("dependsOn", [])), ("Supersedes", rec.get("supersedes", [])), ("Superseded by", superseded_by(decisions).get(rec["id"], []))):
        for did in ids:
            other = decisions.get(did)
            print(f"{label}: {did} · {other['title'] if other else '(not visible on any fetched branch)'}")
    if rec.get("produces"):
        print("Produces:")
        files = repo_files()
        for pattern in rec["produces"]:
            hits = [f for f in files if path_matches(f, pattern)]
            print(f"  {pattern}  ({len(hits)} file(s) on this branch)")


def cmd_why(args):
    target = args.path.lstrip("./")
    cfg = load_lanes()
    view = collect(fetch_first=not args.no_fetch)
    decisions = view_decisions(view)
    eff = effective_status(decisions)
    print(f"{target}: owned by lane {owner_of(target, cfg) or '(nobody)'}")
    ids = covering(target, decisions, eff)
    if not ids:
        print("  No decision covers this file on any fetched branch.")
    for did in ids:
        rec = decisions[did]
        session = rec.get("session", {})
        print(f"  {did} [{eff[did]}] {rec['title']}\n    {rec['decision'][:300]}\n    session {session.get('url') or session.get('id')} · branch {session.get('branch')} · {rec['createdAt']}")
    log = git_ok("log", "-n", "5", "--format=    %h %cs %s", "--", target)
    if log:
        print("  Recent commits:\n" + log.rstrip())


def cmd_context(args):
    cfg = load_lanes()
    lane = args.lane or my_lane()
    lanes = lane_map(cfg)
    if lane not in lanes:
        raise CoordError(f"Unknown lane '{lane}'")
    view = collect(fetch_first=not args.no_fetch)
    decisions = view_decisions(view)
    eff = effective_status(decisions)
    info = lanes[lane]
    print(f"{info['name']} ({lane})\n  {info['mission']}\n  owns: {', '.join(info['owns'])}\n  depends on: {', '.join(info['dependsOn']) or 'nothing'}")
    status = view["status"].get(lane)
    if status:
        print(f"\nSTATUS {status['health']} {status['progress']}% · {ago(status['updatedAt'])} · {status['summary']}")
        for label in ("now", "next", "blockers"):
            for item in status.get(label, []):
                print(f"  {label}: {item}")
    print("\nSESSIONS (reopen these to recover the conversation behind each decision)")
    for s in latest_sessions(view, lane) or []:
        print(f"  {s.get('url') or s.get('sessionId')} · branch {s.get('branch')} · started {s.get('startedAt')} · seen {ago(s.get('lastSeenAt'))} · {s.get('purpose', '')}")
    own = sorted((r for r in decisions.values() if r.get("lane") == lane), key=lambda r: r["id"])
    print("\nDECISIONS")
    for rec in own:
        print(f"  {rec['id']} [{eff[rec['id']]}] {rec['title']}")
    msgs = inbox_for(view, lane)[:10]
    if msgs:
        print("\nINBOX")
        for msg in msgs:
            print(render_message(msg))
    events = sorted((e for e in view["events"].values() if e.get("lane") == lane), key=lambda e: e.get("ts", ""), reverse=True)[:10]
    if events:
        print("\nRECENT EVENTS")
        for event in events:
            print(f"  {event['ts']} {event['kind']:<8} {event['ref']} · {event['summary'][:100]}")


def cmd_build(args):
    changed = write_build()
    print("Spec up to date." if not changed else "Rebuilt: " + ", ".join(changed))


def cmd_validate(args):
    errors, warnings = validate(base=args.base)
    for warning in warnings:
        print(f"warning: {warning}")
    for error in errors:
        print(f"ERROR: {error}")
    if errors:
        print(f"\n{len(errors)} error(s). The protocol is in coord/README.md.")
        return 1
    print(f"Coordination checks passed ({len(warnings)} warning(s)).")
    return 0


def site_data(view: dict) -> dict:
    cfg = view["lanes"]
    decisions = view_decisions(view)
    eff = effective_status(decisions)
    sup_by = superseded_by(decisions)
    decision_rows = []
    for did, entry in view["decisions"].items():
        rec = entry["record"]
        decision_rows.append({**rec, "effectiveStatus": eff[did], "supersededBy": sup_by.get(did, []), "branches": sorted(set(entry["branches"])), "conflict": len(entry["bodies"]) > 1})
    decision_rows.sort(key=lambda r: r.get("createdAt", ""), reverse=True)
    trace = {}
    for lane in cfg["lanes"]:
        picked = pick_trace(view, lane["id"])
        trace[lane["id"]] = picked["files"] if picked else []
    events = sorted(view["events"].values(), key=lambda e: e.get("ts", ""), reverse=True)[:400]
    return {
        "schemaVersion": 1,
        "generatedAt": now_iso(),
        "project": cfg["project"],
        "lanes": cfg["lanes"],
        "status": view["status"],
        "decisions": decision_rows,
        "messages": sorted(view["messages"].values(), key=lambda m: m.get("createdAt", ""), reverse=True)[:300],
        "sessions": sorted(view["sessions"].values(), key=lambda s: s.get("lastSeenAt", ""), reverse=True),
        "events": events,
        "trace": trace,
        "branches": [{"name": b["name"], "sha": b["sha"][:7], "committedAt": b["committedAt"], "subject": b["subject"]} for b in view["branches"]],
        "parseErrors": view["parseErrors"],
    }


def cmd_site(args):
    view = collect(fetch_first=not args.no_fetch, include_worktree=not args.refs_only)
    data = site_data(view)
    out = Path(args.out)
    out.mkdir(parents=True, exist_ok=True)
    template = (ROOT / "site" / "dashboard.html").read_text(encoding="utf-8")
    payload = json.dumps(data, ensure_ascii=False, indent=1)
    write_text(out / "data.json", payload + "\n")
    if args.fragment:
        inline = json.dumps(data, ensure_ascii=False).replace("</", "<\\/")
        page = template.replace("<!--PEAK_INLINE_DATA-->", f"<script>window.__PEAK_DATA__ = {inline};</script>")
        write_text(out / "dashboard.html", page)
        print(f"Wrote {out / 'dashboard.html'} and data.json ({len(data['decisions'])} decisions, {len(data['branches'])} branches)")
    else:
        page = (
            '<!doctype html>\n<html lang="en">\n<head>\n<meta charset="utf-8">\n'
            '<meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">\n</head>\n<body>\n'
            + template
            + "\n</body>\n</html>\n"
        )
        write_text(out / "index.html", page)
        print(f"Wrote {out / 'index.html'} and data.json ({len(data['decisions'])} decisions, {len(data['branches'])} branches)")


# ---------------------------------------------------------------------------
# Hooks. Each reads the hook payload on stdin. Exit 2 blocks the action and
# shows stderr to Claude; any internal error is reported and never blocks.


def _deny(message: str) -> int:
    print(f"[coord] {message}", file=sys.stderr)
    return 2


def hook_session_start(payload: dict) -> int:
    cfg = load_lanes()
    lanes = lane_map(cfg)
    state = load_state()
    if payload.get("source") in (None, "startup") or "startHead" not in state:
        state["startHead"] = head_sha()
        state["sessionStartedAt"] = now_iso()
        save_state(state)
    fetched = fetch(force=True)
    lane = my_lane()
    if lane and lane in lanes:
        touch_session(lane)
    view = collect()
    ref = session_ref()
    out = ["# Peak State coordination · required protocol (CLAUDE.md, coord/README.md)", ""]
    if lane and lane in lanes:
        info = lanes[lane]
        out += [
            f"You are lane `{lane}` ({info['name']}) in session {ref['url'] or ref['id']} on branch {ref['branch']}.",
            f"Brief: docs/hackathon/lanes/{lane}.md · spec: spec/{lane}.md · you own: {', '.join(info['owns'])}",
        ]
    else:
        out += [
            "You have NOT claimed a lane, so edits are blocked. If your task names a lane, claim it first:",
            "  python3 tools/coord.py claim <lane> --purpose '<one line>'",
            "Lanes: " + "; ".join(f"{l['id']} ({l['name']})" for l in cfg["lanes"]),
        ]
    out += ["", render_board(view, lane)]
    if lane:
        msgs = inbox_for(view, lane)[:8]
        if msgs:
            out += ["", f"INBOX for {lane} (newest first)"] + [render_message(m) for m in msgs]
            update_state(seen=sorted(set(load_state().get("seen", [])) | {m["id"] for m in msgs})[-1000:])
    out += ["", LOOP_TEXT]
    if not fetched:
        out.append("(git fetch failed; the board shows the last fetched state)")
    print("\n".join(out))
    return 0


def hook_prompt(payload: dict) -> int:
    lane = my_lane()
    if not lane:
        print("[coord] No lane claimed yet: python3 tools/coord.py claim <lane> --purpose '…' before editing.")
        return 0
    fetch()
    view = collect()
    state = load_state()
    seen = set(state.get("seen", []))
    new = [m for m in inbox_for(view, lane) if m["id"] not in seen]
    lines = []
    if new:
        lines.append(f"[coord] {len(new)} new message(s) for lane {lane}:")
        lines += [render_message(m) for m in new[:6]]
        update_state(seen=sorted(seen | {m["id"] for m in new})[-1000:])
    status = view["status"].get(lane)
    updated = parse_iso((status or {}).get("updatedAt"))
    if status is None or (updated and (datetime.now(timezone.utc) - updated).total_seconds() > STATUS_STALE_MINUTES * 60):
        lines.append(f"[coord] Lane status is {ago((status or {}).get('updatedAt'))}. Refresh it when you reach a milestone: python3 tools/coord.py status --summary '…'")
    if lines:
        print("\n".join(lines))
    return 0


def hook_pre_edit(payload: dict) -> int:
    tool_input = payload.get("tool_input") or {}
    raw = tool_input.get("file_path") or tool_input.get("notebook_path")
    if not raw:
        return 0
    target = Path(raw)
    if not target.is_absolute():
        target = Path(payload.get("cwd") or ROOT) / target
    try:
        path = target.resolve().relative_to(ROOT.resolve()).as_posix()
    except ValueError:
        return 0  # outside the repository
    if path.startswith(".git/"):
        return 0
    cfg = load_lanes()
    if is_generated(path, cfg):
        return _deny(f"{path} is a coordination record or generated spec. Write it with python3 tools/coord.py (decide, status, msg, build), never by hand.")
    lane = my_lane()
    if not lane:
        return _deny("Claim a lane before editing: python3 tools/coord.py claim <lane> --purpose '…'. Lanes: " + ", ".join(lane_map(cfg)))
    owner = owner_of(path, cfg)
    if owner == lane or path in load_state().get("borrowed", []):
        return 0
    if owner is None:
        if lane == "coord":
            return 0
        owns = ", ".join(lane_map(cfg).get(lane, {}).get("owns", []))
        return _deny(f"{path} is outside every lane's paths. Put it under your paths ({owns}) or ask coord: python3 tools/coord.py msg coord --subject 'ownership for {path}' --body '…'")
    return _deny(
        f"{path} belongs to lane '{owner}'. Ask them: python3 tools/coord.py msg {owner} --subject '…' --body '…'. "
        f"If the change is agreed, record it and unlock the file: python3 tools/coord.py borrow {path} --reason '…'"
    )


PUSH_RE = re.compile(
    r"(?:^|[;&|(\n]|&&|\|\|)\s*(?:[A-Za-z_][A-Za-z0-9_]*=\S*\s+)*git(?:\s+-C\s+\S+|\s+-c\s+\S+|\s+--[a-z-]+(?:=\S+)?)*\s+push\b"
)
HEREDOC_RE = re.compile(r"<<-?\s*['\"]?([A-Za-z_][A-Za-z0-9_]*)['\"]?")


def strip_heredocs(command: str) -> str:
    """Drop heredoc bodies so file contents that mention `git push` are not commands."""
    kept, terminator = [], None
    for line in command.split("\n"):
        if terminator:
            if line.strip() == terminator:
                terminator = None
            continue
        kept.append(line)
        match = HEREDOC_RE.search(line)
        if match:
            terminator = match.group(1)
    return "\n".join(kept)


def is_push(command: str) -> bool:
    return bool(PUSH_RE.search(strip_heredocs(command)))


def hook_pre_bash(payload: dict) -> int:
    command = (payload.get("tool_input") or {}).get("command", "")
    if not is_push(command):
        return 0
    cfg = load_lanes()
    problems = []
    changed = write_build(cfg)
    stages_and_commits = re.search(r"\bgit\s+add\b", command) and re.search(r"\bgit\s+commit\b", command)
    if changed and not stages_and_commits:
        problems.append(f"Regenerated {len(changed)} spec file(s): {', '.join(changed)}. Commit them, then push again.")
    # Decisions already on main, or already present when this session began, are append-only.
    bases = [f"origin/{cfg['project']['defaultBranch']}", load_state().get("startHead")]
    errors, _ = validate(base=[b for b in bases if b and git_ok("rev-parse", "--verify", "--quiet", b)])
    errors = [e for e in errors if not e.startswith("Generated spec is out of date")] if changed else errors
    if errors:
        problems.append("Coordination check failed:\n  - " + "\n  - ".join(errors[:15]))
    lane = my_lane()
    if lane and not (COORD / "status" / f"{lane}.json").exists():
        problems.append(f"Lane {lane} has no status on this branch. Post one: python3 tools/coord.py status --summary '…'")
    return _deny("\n".join(problems)) if problems else 0


def _session_changes(cfg: dict) -> list:
    # startHead is recorded by the SessionStart hook. Without it, only
    # uncommitted changes count, so a session that never ran the hook is not
    # blamed for commits it inherited.
    start = load_state().get("startHead")
    changed = set()
    if start:
        diff = git_ok("diff", "-z", "--name-only", start, "HEAD") or ""
        changed |= {f for f in diff.split("\0") if f}
    porcelain = git_ok("status", "-z", "--porcelain", "--untracked-files=all") or ""
    for item in porcelain.split("\0"):
        if len(item) > 3 and item[2] == " ":
            changed.add(item[3:])
    return sorted(f for f in changed if (ROOT / f).is_file() and not is_generated(f, cfg))


def hook_stop(payload: dict) -> int:
    if payload.get("stop_hook_active"):
        return 0
    cfg = load_lanes()
    work = _session_changes(cfg)
    if not work:
        return 0
    lane = my_lane()
    problems = []
    if not lane:
        problems.append("Claim the lane this work belongs to: python3 tools/coord.py claim <lane> --purpose '…'")
    else:
        sid = session_ref()["id"]
        decisions = local_decisions()
        eff = effective_status(decisions)
        if not any(rec.get("session", {}).get("id") == sid for rec in decisions.values()):
            problems.append("This session changed files but logged no decision. Record what you decided and what it produced: python3 tools/coord.py decide --title … --decision … --context … --produces …")
        uncovered = [f for f in work if not covering(f, decisions, eff)]
        if uncovered:
            problems.append("Not covered by any decision's --produces: " + ", ".join(uncovered[:10]))
        status_path = COORD / "status" / f"{lane}.json"
        newest = max((ROOT / f).stat().st_mtime for f in work)
        status_time = None
        if status_path.exists():
            try:
                status_time = parse_iso(read_json(status_path).get("updatedAt"))
            except ValueError:
                status_time = None
        if status_time is None or status_time.timestamp() < newest - 5:
            problems.append("Your lane status predates your latest change. Update it: python3 tools/coord.py status --summary … --now … --next …")
        expected = build_outputs(cfg, decisions)
        if any(not (ROOT / p).exists() or (ROOT / p).read_text(encoding="utf-8") != text for p, text in expected.items()):
            problems.append("Spec is stale: python3 tools/coord.py build")
    if problems:
        print("[coord] Before you stop, close the loop:\n- " + "\n- ".join(problems) + "\nThen commit and push your branch.", file=sys.stderr)
        return 2
    return 0


HOOKS = {
    "session-start": hook_session_start,
    "prompt": hook_prompt,
    "pre-edit": hook_pre_edit,
    "pre-bash": hook_pre_bash,
    "stop": hook_stop,
}


def cmd_hook(args):
    if os.environ.get("PEAK_COORD", "").lower() in ("off", "0", "false"):
        return 0
    try:
        raw = sys.stdin.read() if not sys.stdin.isatty() else ""
        payload = json.loads(raw) if raw.strip() else {}
    except ValueError:
        payload = {}
    try:
        return HOOKS[args.event](payload)
    except Exception as exc:  # a coordination bug must never wedge a session
        print(f"[coord] {args.event} hook error, ignored: {exc}", file=sys.stderr)
        return 0


# ---------------------------------------------------------------------------
# CLI


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="coord.py", description="Peak State coordination: decisions, status, messages, spec and hooks.")
    sub = parser.add_subparsers(dest="command", required=True)

    p = sub.add_parser("claim", help="claim a lane for this session")
    p.add_argument("lane")
    p.add_argument("--purpose", default="")
    p.add_argument("--no-fetch", action="store_true")
    p.set_defaults(func=cmd_claim)

    p = sub.add_parser("decide", help="log a decision and rebuild the spec")
    p.add_argument("--title", help="4 to 120 characters")
    p.add_argument("--decision")
    p.add_argument("--context")
    p.add_argument("--type", choices=["scope", "product", "technical", "contract", "process", "research"])
    p.add_argument("--status", choices=["proposed", "accepted"])
    p.add_argument("--produces", nargs="*", default=[])
    p.add_argument("--depends-on", dest="dependsOn", nargs="*", default=[])
    p.add_argument("--supersedes", nargs="*", default=[])
    p.add_argument("--alternatives", nargs="*", default=[])
    p.add_argument("--consequences")
    p.add_argument("--author")
    p.add_argument("--lane", help="defaults to your claimed lane")
    p.add_argument("--json", help="read fields from a JSON file, or - for stdin")
    p.set_defaults(func=cmd_decide)

    for name, status in (("accept", "accepted"), ("reject", "rejected")):
        p = sub.add_parser(name, help=f"mark a proposed decision {status}")
        p.add_argument("id")
        p.add_argument("--by", help="who decided (a person's name, or claude)")
        p.add_argument("--note", default="")
        p.set_defaults(func=lambda a, s=status: cmd_set_decision_status(a, s))

    p = sub.add_parser("status", help="overwrite your lane status")
    p.add_argument("--summary", required=True)
    p.add_argument("--health", choices=["green", "amber", "red", "idle"])
    p.add_argument("--phase")
    p.add_argument("--progress", type=int)
    p.add_argument("--now", action="append")
    p.add_argument("--next", action="append")
    p.add_argument("--blocker", action="append")
    p.add_argument("--clear-blockers", action="store_true")
    p.add_argument("--lane")
    p.set_defaults(func=cmd_status)

    p = sub.add_parser("msg", help="message a lane, all, or human")
    p.add_argument("to")
    p.add_argument("--subject", required=True)
    p.add_argument("--body", required=True)
    p.add_argument("--refs", nargs="*", default=[])
    p.add_argument("--reply-to")
    p.add_argument("--lane", help="sender; defaults to your claimed lane")
    p.set_defaults(func=cmd_msg)

    p = sub.add_parser("borrow", help="unlock another lane's file after agreeing the change")
    p.add_argument("path")
    p.add_argument("--reason", required=True)
    p.add_argument("--refs", nargs="*", default=[])
    p.set_defaults(func=cmd_borrow)

    p = sub.add_parser("board", help="status of every lane across every branch")
    p.add_argument("--no-fetch", action="store_true")
    p.add_argument("--json", action="store_true")
    p.add_argument("--limit", type=int, default=10)
    p.set_defaults(func=cmd_board)

    p = sub.add_parser("inbox", help="messages for your lane from every branch")
    p.add_argument("--all", action="store_true")
    p.add_argument("--lane")
    p.add_argument("--limit", type=int, default=20)
    p.add_argument("--no-fetch", action="store_true")
    p.set_defaults(func=cmd_inbox)

    p = sub.add_parser("show", help="one decision, its links and the session that made it")
    p.add_argument("id")
    p.add_argument("--no-fetch", action="store_true")
    p.set_defaults(func=cmd_show)

    p = sub.add_parser("why", help="which decisions and sessions produced a file")
    p.add_argument("path")
    p.add_argument("--no-fetch", action="store_true")
    p.set_defaults(func=cmd_why)

    p = sub.add_parser("context", help="everything needed to resume a lane")
    p.add_argument("lane", nargs="?")
    p.add_argument("--no-fetch", action="store_true")
    p.set_defaults(func=cmd_context)

    p = sub.add_parser("build", help="regenerate spec/ and coord/trace/")
    p.set_defaults(func=cmd_build)

    p = sub.add_parser("validate", help="check records, ownership, coverage and spec freshness")
    p.add_argument("--base", help="also check decision immutability against this ref, e.g. origin/main")
    p.set_defaults(func=cmd_validate)

    p = sub.add_parser("site", help="build the dashboard from every branch")
    p.add_argument("--out", required=True)
    p.add_argument("--fragment", action="store_true", help="inline the data into a page fragment (for an Artifact)")
    p.add_argument("--refs-only", action="store_true", help="ignore the working tree (CI)")
    p.add_argument("--no-fetch", action="store_true")
    p.set_defaults(func=cmd_site)

    p = sub.add_parser("hook", help="Claude Code hook entry point")
    p.add_argument("event", choices=sorted(HOOKS))
    p.set_defaults(func=cmd_hook)
    return parser


def main(argv=None) -> int:
    args = build_parser().parse_args(argv)
    try:
        result = args.func(args)
    except CoordError as exc:
        print(f"coord: {exc}", file=sys.stderr)
        return 1
    return result if isinstance(result, int) else 0


if __name__ == "__main__":
    sys.exit(main())
