// GENERATED by contracts/fixtures/_generate.py. Do not edit.
// The JSON fixtures as typed constants: tsc checks each against its type, and lanes can import them.

import type { OnboardingEvent } from "./onboarding.ts";
import type { ProfileV2 } from "./profile.ts";
import type { RepSession } from "./reps.ts";
import type { CalibrationSummary, DetectionEvent, SignalFrame } from "./signals.ts";

/** fixtures/profile.demo.json */
export const profileDemo: ProfileV2 = {
  "schemaVersion": 2,
  "profileId": "profile_demo_ada",
  "displayName": "Ada",
  "createdAt": "2026-10-03T15:00:00Z",
  "confirmedAt": "2026-10-03T15:01:35Z",
  "states": [
    {
      "id": "calm-before-pitch",
      "label": "calm before a pitch",
      "words": "Like the room is already mine and there's no rush",
      "memoryCue": "the Berlin demo",
      "leverage": "So I stop rushing the part that matters",
      "strategy": {
        "steps": [
          {
            "modality": "visual",
            "direction": "external",
            "content": "the first face in the room looking up at me",
            "submodalities": {
              "core": {
                "location": "center",
                "size": "life-size",
                "distance": "close",
                "brightness": "bright",
                "perspective": "associated"
              },
              "extended": {
                "motion": "movie"
              },
              "words": {
                "distance": "right there, like across a table"
              }
            },
            "anchorDetail": {
              "kind": "scene",
              "caption": "The first face looking up",
              "details": [
                "warm window light",
                "a coffee cup on the table"
              ]
            }
          },
          {
            "modality": "auditory",
            "direction": "internal",
            "content": "'here we go, slow'",
            "submodalities": {
              "core": {
                "source": "my own voice",
                "volume": "quiet",
                "location": "inside-head"
              },
              "extended": {
                "tempo": "slow"
              }
            }
          },
          {
            "modality": "kinesthetic",
            "direction": "internal",
            "content": "warmth spreading through my chest",
            "submodalities": {
              "core": {
                "bodyLocation": "chest",
                "intensity": 8,
                "movement": "moving"
              },
              "extended": {
                "temperature": "warm",
                "direction": "spreading"
              }
            }
          }
        ],
        "fullyInAt": 2,
        "confirmed": true
      },
      "anchorStep": 0,
      "contrast": {
        "label": "stuck on a small email",
        "submodalities": {
          "visual": {
            "core": {
              "location": "lower-left",
              "size": "small",
              "distance": "far",
              "brightness": "dim",
              "perspective": "dissociated"
            }
          },
          "auditory": {
            "core": {
              "source": "my own voice",
              "volume": "loud",
              "location": "inside-head"
            },
            "extended": {
              "tempo": "fast"
            }
          },
          "kinesthetic": {
            "core": {
              "bodyLocation": "stomach",
              "intensity": 3,
              "movement": "still"
            }
          }
        },
        "prefilled": true
      },
      "differences": [
        {
          "stepIndex": 0,
          "modality": "visual",
          "attribute": "location",
          "peak": "center",
          "contrast": "lower-left",
          "ratingDelta": 1
        },
        {
          "stepIndex": 0,
          "modality": "visual",
          "attribute": "size",
          "peak": "life-size",
          "contrast": "small",
          "ratingDelta": 1
        },
        {
          "stepIndex": 0,
          "modality": "visual",
          "attribute": "distance",
          "peak": "close",
          "contrast": "far",
          "ratingDelta": 3
        },
        {
          "stepIndex": 0,
          "modality": "visual",
          "attribute": "brightness",
          "peak": "bright",
          "contrast": "dim",
          "ratingDelta": 2
        },
        {
          "stepIndex": 0,
          "modality": "visual",
          "attribute": "perspective",
          "peak": "associated",
          "contrast": "dissociated",
          "ratingDelta": 1
        },
        {
          "stepIndex": 1,
          "modality": "auditory",
          "attribute": "volume",
          "peak": "quiet",
          "contrast": "loud",
          "ratingDelta": 2
        },
        {
          "stepIndex": 1,
          "modality": "auditory",
          "attribute": "tempo",
          "peak": "slow",
          "contrast": "fast",
          "ratingDelta": 1
        },
        {
          "stepIndex": 2,
          "modality": "kinesthetic",
          "attribute": "movement",
          "peak": "moving",
          "contrast": "still",
          "ratingDelta": 1
        }
      ],
      "drivers": [
        2,
        3,
        5
      ],
      "recode": {
        "appliedDrivers": [
          2,
          3,
          5
        ]
      },
      "test": {
        "before": 3,
        "after": 7
      },
      "futurePace": {
        "situation": "Thursday's board pitch"
      },
      "calibration": {
        "peak": {
          "stateId": "calm-before-pitch",
          "phase": "peak",
          "source": "simulator",
          "hr": {
            "mean": 68.2,
            "sd": 2.1
          },
          "lnRmssd": {
            "mean": 3.95,
            "sd": 0.12
          },
          "windows": 5,
          "seconds": 40,
          "quality": "ok",
          "speechExcludedSeconds": 8,
          "recordedAt": "2026-10-03T15:00:40Z",
          "rating": 8
        },
        "contrast": {
          "stateId": "calm-before-pitch",
          "phase": "contrast",
          "source": "simulator",
          "hr": {
            "mean": 79.5,
            "sd": 3.0
          },
          "lnRmssd": {
            "mean": 3.45,
            "sd": 0.15
          },
          "windows": 3,
          "seconds": 24,
          "quality": "ok",
          "speechExcludedSeconds": 4,
          "recordedAt": "2026-10-03T15:01:10Z",
          "rating": 3,
          "separability": {
            "separable": true,
            "hr": 4.36,
            "lnRmssd": 3.68
          }
        }
      }
    }
  ]
};

/** fixtures/profile.three-states.json */
export const profileThreeStates: ProfileV2 = {
  "schemaVersion": 2,
  "profileId": "profile_demo_three",
  "displayName": "Ada",
  "createdAt": "2026-10-03T15:00:00Z",
  "confirmedAt": "2026-10-03T15:01:35Z",
  "states": [
    {
      "id": "calm-before-pitch",
      "label": "calm before a pitch",
      "words": "Like the room is already mine and there's no rush",
      "memoryCue": "the Berlin demo",
      "leverage": "So I stop rushing the part that matters",
      "strategy": {
        "steps": [
          {
            "modality": "visual",
            "direction": "external",
            "content": "the first face in the room looking up at me",
            "submodalities": {
              "core": {
                "location": "center",
                "size": "life-size",
                "distance": "close",
                "brightness": "bright",
                "perspective": "associated"
              },
              "extended": {
                "motion": "movie"
              },
              "words": {
                "distance": "right there, like across a table"
              }
            },
            "anchorDetail": {
              "kind": "scene",
              "caption": "The first face looking up",
              "details": [
                "warm window light",
                "a coffee cup on the table"
              ]
            }
          },
          {
            "modality": "auditory",
            "direction": "internal",
            "content": "'here we go, slow'",
            "submodalities": {
              "core": {
                "source": "my own voice",
                "volume": "quiet",
                "location": "inside-head"
              },
              "extended": {
                "tempo": "slow"
              }
            }
          },
          {
            "modality": "kinesthetic",
            "direction": "internal",
            "content": "warmth spreading through my chest",
            "submodalities": {
              "core": {
                "bodyLocation": "chest",
                "intensity": 8,
                "movement": "moving"
              },
              "extended": {
                "temperature": "warm",
                "direction": "spreading"
              }
            }
          }
        ],
        "fullyInAt": 2,
        "confirmed": true
      },
      "anchorStep": 0,
      "contrast": {
        "label": "stuck on a small email",
        "submodalities": {
          "visual": {
            "core": {
              "location": "lower-left",
              "size": "small",
              "distance": "far",
              "brightness": "dim",
              "perspective": "dissociated"
            }
          },
          "auditory": {
            "core": {
              "source": "my own voice",
              "volume": "loud",
              "location": "inside-head"
            },
            "extended": {
              "tempo": "fast"
            }
          },
          "kinesthetic": {
            "core": {
              "bodyLocation": "stomach",
              "intensity": 3,
              "movement": "still"
            }
          }
        },
        "prefilled": true
      },
      "differences": [
        {
          "stepIndex": 0,
          "modality": "visual",
          "attribute": "location",
          "peak": "center",
          "contrast": "lower-left",
          "ratingDelta": 1
        },
        {
          "stepIndex": 0,
          "modality": "visual",
          "attribute": "size",
          "peak": "life-size",
          "contrast": "small",
          "ratingDelta": 1
        },
        {
          "stepIndex": 0,
          "modality": "visual",
          "attribute": "distance",
          "peak": "close",
          "contrast": "far",
          "ratingDelta": 3
        },
        {
          "stepIndex": 0,
          "modality": "visual",
          "attribute": "brightness",
          "peak": "bright",
          "contrast": "dim",
          "ratingDelta": 2
        },
        {
          "stepIndex": 0,
          "modality": "visual",
          "attribute": "perspective",
          "peak": "associated",
          "contrast": "dissociated",
          "ratingDelta": 1
        },
        {
          "stepIndex": 1,
          "modality": "auditory",
          "attribute": "volume",
          "peak": "quiet",
          "contrast": "loud",
          "ratingDelta": 2
        },
        {
          "stepIndex": 1,
          "modality": "auditory",
          "attribute": "tempo",
          "peak": "slow",
          "contrast": "fast",
          "ratingDelta": 1
        },
        {
          "stepIndex": 2,
          "modality": "kinesthetic",
          "attribute": "movement",
          "peak": "moving",
          "contrast": "still",
          "ratingDelta": 1
        }
      ],
      "drivers": [
        2,
        3,
        5
      ],
      "recode": {
        "appliedDrivers": [
          2,
          3,
          5
        ]
      },
      "test": {
        "before": 3,
        "after": 7
      },
      "futurePace": {
        "situation": "Thursday's board pitch"
      },
      "calibration": {
        "peak": {
          "stateId": "calm-before-pitch",
          "phase": "peak",
          "source": "simulator",
          "hr": {
            "mean": 68.2,
            "sd": 2.1
          },
          "lnRmssd": {
            "mean": 3.95,
            "sd": 0.12
          },
          "windows": 5,
          "seconds": 40,
          "quality": "ok",
          "speechExcludedSeconds": 8,
          "recordedAt": "2026-10-03T15:00:40Z",
          "rating": 8
        },
        "contrast": {
          "stateId": "calm-before-pitch",
          "phase": "contrast",
          "source": "simulator",
          "hr": {
            "mean": 79.5,
            "sd": 3.0
          },
          "lnRmssd": {
            "mean": 3.45,
            "sd": 0.15
          },
          "windows": 3,
          "seconds": 24,
          "quality": "ok",
          "speechExcludedSeconds": 4,
          "recordedAt": "2026-10-03T15:01:10Z",
          "rating": 3,
          "separability": {
            "separable": true,
            "hr": 4.36,
            "lnRmssd": 3.68
          }
        }
      }
    },
    {
      "id": "playful-with-kids",
      "label": "playful with my kids",
      "words": "Silly and light, nothing to prove",
      "memoryCue": "the pillow fort",
      "leverage": null,
      "strategy": {
        "steps": [
          {
            "modality": "auditory",
            "direction": "external",
            "content": "their laughing",
            "submodalities": {
              "core": {
                "source": "the kids",
                "volume": "loud",
                "location": "all-around"
              }
            },
            "anchorDetail": {
              "kind": "song",
              "title": "Here Comes the Sun",
              "artist": "The Beatles",
              "moment": "the first 'little darling'"
            }
          },
          {
            "modality": "kinesthetic",
            "direction": "internal",
            "content": "a bounce in my legs",
            "submodalities": {
              "core": {
                "bodyLocation": "legs",
                "intensity": 7,
                "movement": "moving"
              },
              "extended": {
                "rhythm": "pulsing"
              }
            }
          }
        ],
        "fullyInAt": 1,
        "confirmed": true
      },
      "anchorStep": 0,
      "contrast": null,
      "differences": [],
      "drivers": [],
      "recode": null,
      "test": null,
      "futurePace": null,
      "calibration": {
        "peak": null,
        "contrast": null
      }
    },
    {
      "id": "confident",
      "label": "confident",
      "words": "I already know the answer",
      "strategy": {
        "steps": [
          {
            "modality": "kinesthetic",
            "direction": "internal",
            "content": "feet planted, chest open",
            "submodalities": {
              "core": {
                "bodyLocation": "feet",
                "intensity": 6,
                "movement": "still"
              }
            },
            "anchorDetail": {
              "kind": "body",
              "gesture": "press thumb and forefinger together"
            }
          },
          {
            "modality": "visual",
            "direction": "internal",
            "content": "the finish line photo",
            "submodalities": {
              "core": {
                "distance": "close",
                "brightness": "bright"
              }
            }
          },
          {
            "modality": "other",
            "direction": "external",
            "content": "the smell of the track",
            "submodalities": {
              "words": {
                "smell": "rubber and cut grass"
              }
            }
          }
        ],
        "fullyInAt": 2,
        "confirmed": true
      },
      "anchorStep": 0,
      "contrast": null,
      "differences": [],
      "drivers": [],
      "recode": null,
      "test": null,
      "futurePace": null,
      "calibration": {
        "peak": null,
        "contrast": null
      }
    }
  ]
};

/** fixtures/profile.draft.json */
export const profileDraft: ProfileV2 = {
  "schemaVersion": 2,
  "profileId": "profile_demo_ada",
  "displayName": "Ada",
  "createdAt": "2026-10-03T15:00:00Z",
  "confirmedAt": null,
  "states": [
    {
      "id": "calm-before-pitch",
      "label": "calm before a pitch",
      "words": "Like the room is already mine and there's no rush",
      "memoryCue": "the Berlin demo",
      "leverage": "So I stop rushing the part that matters",
      "strategy": {
        "steps": [
          {
            "modality": "visual",
            "direction": "external",
            "content": "the first face in the room looking up at me",
            "submodalities": {
              "core": {
                "location": "center",
                "size": "life-size",
                "distance": "close",
                "brightness": "bright",
                "perspective": "associated"
              },
              "extended": {
                "motion": "movie"
              },
              "words": {
                "distance": "right there, like across a table"
              }
            },
            "anchorDetail": {
              "kind": "scene",
              "caption": "The first face looking up",
              "details": [
                "warm window light",
                "a coffee cup on the table"
              ]
            }
          },
          {
            "modality": "auditory",
            "direction": "internal",
            "content": "'here we go, slow'",
            "submodalities": {
              "core": {
                "source": "my own voice",
                "volume": "quiet",
                "location": "inside-head"
              },
              "extended": {
                "tempo": "slow"
              }
            }
          },
          {
            "modality": "kinesthetic",
            "direction": "internal",
            "content": "warmth spreading through my chest",
            "submodalities": {
              "core": {
                "bodyLocation": "chest",
                "intensity": 8,
                "movement": "moving"
              },
              "extended": {
                "temperature": "warm",
                "direction": "spreading"
              }
            }
          }
        ],
        "fullyInAt": 2,
        "confirmed": false
      },
      "anchorStep": null,
      "contrast": null,
      "differences": [],
      "drivers": [],
      "recode": null,
      "test": null,
      "futurePace": null,
      "calibration": {
        "peak": {
          "stateId": "calm-before-pitch",
          "phase": "peak",
          "source": "simulator",
          "hr": {
            "mean": 68.2,
            "sd": 2.1
          },
          "lnRmssd": {
            "mean": 3.95,
            "sd": 0.12
          },
          "windows": 5,
          "seconds": 40,
          "quality": "ok",
          "speechExcludedSeconds": 8,
          "recordedAt": "2026-10-03T15:00:40Z",
          "rating": 8
        },
        "contrast": null
      }
    }
  ]
};

/** fixtures/calibration.peak.json */
export const calibrationPeak: CalibrationSummary = {
  "stateId": "calm-before-pitch",
  "phase": "peak",
  "source": "simulator",
  "hr": {
    "mean": 68.2,
    "sd": 2.1
  },
  "lnRmssd": {
    "mean": 3.95,
    "sd": 0.12
  },
  "windows": 5,
  "seconds": 40,
  "quality": "ok",
  "speechExcludedSeconds": 8,
  "recordedAt": "2026-10-03T15:00:40Z",
  "rating": 8
};

/** fixtures/calibration.contrast.json */
export const calibrationContrast: CalibrationSummary = {
  "stateId": "calm-before-pitch",
  "phase": "contrast",
  "source": "simulator",
  "hr": {
    "mean": 79.5,
    "sd": 3.0
  },
  "lnRmssd": {
    "mean": 3.45,
    "sd": 0.15
  },
  "windows": 3,
  "seconds": 24,
  "quality": "ok",
  "speechExcludedSeconds": 4,
  "recordedAt": "2026-10-03T15:01:10Z",
  "rating": 3,
  "separability": {
    "separable": true,
    "hr": 4.36,
    "lnRmssd": 3.68
  }
};

/** fixtures/frames.drift.json */
export const framesDrift: SignalFrame[] = [
  {
    "t": 1791040200000,
    "source": "simulator",
    "hr": 68.2,
    "rr": [
      905.7
    ],
    "quality": 1.0,
    "label": "baseline"
  },
  {
    "t": 1791040201000,
    "source": "simulator",
    "hr": 68.4,
    "rr": [
      851.2
    ],
    "quality": 1.0,
    "label": "baseline"
  },
  {
    "t": 1791040202000,
    "source": "simulator",
    "hr": 68.6,
    "rr": [
      900.6
    ],
    "quality": 1.0,
    "label": "baseline"
  },
  {
    "t": 1791040203000,
    "source": "simulator",
    "hr": 68.7,
    "rr": [
      847.4
    ],
    "quality": 1.0,
    "label": "baseline"
  },
  {
    "t": 1791040204000,
    "source": "simulator",
    "hr": 68.8,
    "rr": [
      898.1
    ],
    "quality": 1.0,
    "label": "baseline"
  },
  {
    "t": 1791040205000,
    "source": "simulator",
    "hr": 68.8,
    "rr": [
      846.1
    ],
    "quality": 1.0,
    "label": "baseline"
  },
  {
    "t": 1791040206000,
    "source": "simulator",
    "hr": 68.7,
    "rr": [
      899.3
    ],
    "quality": 1.0,
    "label": "baseline"
  },
  {
    "t": 1791040207000,
    "source": "simulator",
    "hr": 68.6,
    "rr": [
      848.7
    ],
    "quality": 1.0,
    "label": "baseline"
  },
  {
    "t": 1791040208000,
    "source": "simulator",
    "hr": 68.5,
    "rr": [
      901.9
    ],
    "quality": 1.0,
    "label": "baseline"
  },
  {
    "t": 1791040209000,
    "source": "simulator",
    "hr": 68.3,
    "rr": [
      852.5
    ],
    "quality": 1.0,
    "label": "baseline"
  },
  {
    "t": 1791040210000,
    "source": "simulator",
    "hr": 68.1,
    "rr": [
      907.0
    ],
    "quality": 1.0,
    "label": "baseline"
  },
  {
    "t": 1791040211000,
    "source": "simulator",
    "hr": 67.9,
    "rr": [
      857.7
    ],
    "quality": 1.0,
    "label": "baseline"
  },
  {
    "t": 1791040212000,
    "source": "simulator",
    "hr": 67.7,
    "rr": [
      912.2
    ],
    "quality": 1.0,
    "label": "baseline"
  },
  {
    "t": 1791040213000,
    "source": "simulator",
    "hr": 67.6,
    "rr": [
      861.6
    ],
    "quality": 1.0,
    "label": "baseline"
  },
  {
    "t": 1791040214000,
    "source": "simulator",
    "hr": 67.6,
    "rr": [
      913.5
    ],
    "quality": 1.0,
    "label": "baseline"
  },
  {
    "t": 1791040215000,
    "source": "simulator",
    "hr": 67.6,
    "rr": [
      861.6
    ],
    "quality": 1.0,
    "label": "baseline"
  },
  {
    "t": 1791040216000,
    "source": "simulator",
    "hr": 67.7,
    "rr": [
      912.2
    ],
    "quality": 1.0,
    "label": "baseline"
  },
  {
    "t": 1791040217000,
    "source": "simulator",
    "hr": 67.9,
    "rr": [
      857.7
    ],
    "quality": 1.0,
    "label": "baseline"
  },
  {
    "t": 1791040218000,
    "source": "simulator",
    "hr": 68.0,
    "rr": [
      908.3
    ],
    "quality": 1.0,
    "label": "baseline"
  },
  {
    "t": 1791040219000,
    "source": "simulator",
    "hr": 68.2,
    "rr": [
      853.8
    ],
    "quality": 1.0,
    "label": "baseline"
  },
  {
    "t": 1791040220000,
    "source": "simulator",
    "hr": 68.4,
    "rr": [
      903.2
    ],
    "quality": 1.0,
    "label": "baseline"
  },
  {
    "t": 1791040221000,
    "source": "simulator",
    "hr": 68.6,
    "rr": [
      848.7
    ],
    "quality": 1.0,
    "label": "baseline"
  },
  {
    "t": 1791040222000,
    "source": "simulator",
    "hr": 68.7,
    "rr": [
      899.3
    ],
    "quality": 1.0,
    "label": "baseline"
  },
  {
    "t": 1791040223000,
    "source": "simulator",
    "hr": 68.8,
    "rr": [
      846.1
    ],
    "quality": 1.0,
    "label": "baseline"
  },
  {
    "t": 1791040224000,
    "source": "simulator",
    "hr": 68.8,
    "rr": [
      898.1
    ],
    "quality": 1.0,
    "label": "baseline"
  },
  {
    "t": 1791040225000,
    "source": "simulator",
    "hr": 68.7,
    "rr": [
      847.4
    ],
    "quality": 1.0,
    "label": "baseline"
  },
  {
    "t": 1791040226000,
    "source": "simulator",
    "hr": 68.6,
    "rr": [
      900.6
    ],
    "quality": 1.0,
    "label": "baseline"
  },
  {
    "t": 1791040227000,
    "source": "simulator",
    "hr": 68.4,
    "rr": [
      851.2
    ],
    "quality": 1.0,
    "label": "baseline"
  },
  {
    "t": 1791040228000,
    "source": "simulator",
    "hr": 68.3,
    "rr": [
      904.4
    ],
    "quality": 1.0,
    "label": "baseline"
  },
  {
    "t": 1791040229000,
    "source": "simulator",
    "hr": 68.1,
    "rr": [
      855.1
    ],
    "quality": 1.0,
    "label": "baseline"
  },
  {
    "t": 1791040230000,
    "source": "simulator",
    "hr": 68.3,
    "rr": [
      904.1
    ],
    "quality": 1.0,
    "label": "drift"
  },
  {
    "t": 1791040231000,
    "source": "simulator",
    "hr": 68.5,
    "rr": [
      850.6
    ],
    "quality": 1.0,
    "label": "drift"
  },
  {
    "t": 1791040232000,
    "source": "simulator",
    "hr": 68.8,
    "rr": [
      897.0
    ],
    "quality": 1.0,
    "label": "drift"
  },
  {
    "t": 1791040233000,
    "source": "simulator",
    "hr": 69.1,
    "rr": [
      843.7
    ],
    "quality": 1.0,
    "label": "drift"
  },
  {
    "t": 1791040234000,
    "source": "simulator",
    "hr": 69.5,
    "rr": [
      887.6
    ],
    "quality": 1.0,
    "label": "drift"
  },
  {
    "t": 1791040235000,
    "source": "simulator",
    "hr": 70.0,
    "rr": [
      833.2
    ],
    "quality": 1.0,
    "label": "drift"
  },
  {
    "t": 1791040236000,
    "source": "simulator",
    "hr": 70.5,
    "rr": [
      874.6
    ],
    "quality": 1.0,
    "label": "drift"
  },
  {
    "t": 1791040237000,
    "source": "simulator",
    "hr": 71.1,
    "rr": [
      820.6
    ],
    "quality": 1.0,
    "label": "drift"
  },
  {
    "t": 1791040238000,
    "source": "simulator",
    "hr": 71.7,
    "rr": [
      859.7
    ],
    "quality": 1.0,
    "label": "drift"
  },
  {
    "t": 1791040239000,
    "source": "simulator",
    "hr": 72.2,
    "rr": [
      808.5
    ],
    "quality": 1.0,
    "label": "drift"
  },
  {
    "t": 1791040240000,
    "source": "simulator",
    "hr": 72.8,
    "rr": [
      846.4
    ],
    "quality": 1.0,
    "label": "drift"
  },
  {
    "t": 1791040241000,
    "source": "simulator",
    "hr": 73.3,
    "rr": [
      796.7
    ],
    "quality": 1.0,
    "label": "drift"
  },
  {
    "t": 1791040242000,
    "source": "simulator",
    "hr": 73.7,
    "rr": [
      835.7
    ],
    "quality": 1.0,
    "label": "drift"
  },
  {
    "t": 1791040243000,
    "source": "simulator",
    "hr": 74.1,
    "rr": [
      788.5
    ],
    "quality": 1.0,
    "label": "drift"
  },
  {
    "t": 1791040244000,
    "source": "simulator",
    "hr": 74.4,
    "rr": [
      827.3
    ],
    "quality": 1.0,
    "label": "drift"
  },
  {
    "t": 1791040245000,
    "source": "simulator",
    "hr": 74.6,
    "rr": [
      783.8
    ],
    "quality": 1.0,
    "label": "drift"
  },
  {
    "t": 1791040246000,
    "source": "simulator",
    "hr": 74.8,
    "rr": [
      822.3
    ],
    "quality": 1.0,
    "label": "drift"
  },
  {
    "t": 1791040247000,
    "source": "simulator",
    "hr": 75.0,
    "rr": [
      780.2
    ],
    "quality": 1.0,
    "label": "drift"
  },
  {
    "t": 1791040248000,
    "source": "simulator",
    "hr": 75.2,
    "rr": [
      817.4
    ],
    "quality": 1.0,
    "label": "drift"
  },
  {
    "t": 1791040249000,
    "source": "simulator",
    "hr": 75.4,
    "rr": [
      776.6
    ],
    "quality": 1.0,
    "label": "drift"
  },
  {
    "t": 1791040250000,
    "source": "simulator",
    "hr": 75.6,
    "rr": [
      812.5
    ],
    "quality": 1.0,
    "label": "drift"
  },
  {
    "t": 1791040251000,
    "source": "simulator",
    "hr": 75.9,
    "rr": [
      772.0
    ],
    "quality": 1.0,
    "label": "drift"
  },
  {
    "t": 1791040252000,
    "source": "simulator",
    "hr": 76.3,
    "rr": [
      804.5
    ],
    "quality": 1.0,
    "label": "drift"
  },
  {
    "t": 1791040253000,
    "source": "simulator",
    "hr": 76.7,
    "rr": [
      764.5
    ],
    "quality": 1.0,
    "label": "drift"
  },
  {
    "t": 1791040254000,
    "source": "simulator",
    "hr": 77.2,
    "rr": [
      794.7
    ],
    "quality": 1.0,
    "label": "drift"
  },
  {
    "t": 1791040255000,
    "source": "simulator",
    "hr": 77.7,
    "rr": [
      755.1
    ],
    "quality": 1.0,
    "label": "drift"
  },
  {
    "t": 1791040256000,
    "source": "simulator",
    "hr": 78.3,
    "rr": [
      783.1
    ],
    "quality": 1.0,
    "label": "drift"
  },
  {
    "t": 1791040257000,
    "source": "simulator",
    "hr": 78.8,
    "rr": [
      745.0
    ],
    "quality": 1.0,
    "label": "drift"
  },
  {
    "t": 1791040258000,
    "source": "simulator",
    "hr": 79.4,
    "rr": [
      771.8
    ],
    "quality": 1.0,
    "label": "drift"
  },
  {
    "t": 1791040259000,
    "source": "simulator",
    "hr": 79.9,
    "rr": [
      735.2
    ],
    "quality": 1.0,
    "label": "drift"
  },
  {
    "t": 1791040260000,
    "source": "simulator",
    "hr": 80.0,
    "rr": [
      765.8
    ],
    "quality": 1.0,
    "label": "drift"
  },
  {
    "t": 1791040261000,
    "source": "simulator",
    "hr": 80.1,
    "rr": [
      733.3
    ],
    "quality": 1.0,
    "label": "drift"
  },
  {
    "t": 1791040262000,
    "source": "simulator",
    "hr": 80.1,
    "rr": [
      764.8
    ],
    "quality": 1.0,
    "label": "drift"
  },
  {
    "t": 1791040263000,
    "source": "simulator",
    "hr": 80.0,
    "rr": [
      734.2
    ],
    "quality": 1.0,
    "label": "drift"
  },
  {
    "t": 1791040264000,
    "source": "simulator",
    "hr": 79.9,
    "rr": [
      766.7
    ],
    "quality": 1.0,
    "label": "drift"
  },
  {
    "t": 1791040265000,
    "source": "simulator",
    "hr": 79.7,
    "rr": [
      737.1
    ],
    "quality": 1.0,
    "label": "drift"
  },
  {
    "t": 1791040266000,
    "source": "simulator",
    "hr": 79.5,
    "rr": [
      770.5
    ],
    "quality": 1.0,
    "label": "drift"
  },
  {
    "t": 1791040267000,
    "source": "simulator",
    "hr": 79.3,
    "rr": [
      740.9
    ],
    "quality": 1.0,
    "label": "drift"
  },
  {
    "t": 1791040268000,
    "source": "simulator",
    "hr": 79.1,
    "rr": [
      774.3
    ],
    "quality": 1.0,
    "label": "drift"
  },
  {
    "t": 1791040269000,
    "source": "simulator",
    "hr": 79.0,
    "rr": [
      743.7
    ],
    "quality": 1.0,
    "label": "drift"
  },
  {
    "t": 1791040270000,
    "source": "simulator",
    "hr": 78.9,
    "rr": [
      776.2
    ],
    "quality": 0.9,
    "label": "rep"
  },
  {
    "t": 1791040271000,
    "source": "simulator",
    "hr": 78.7,
    "rr": [
      746.5
    ],
    "quality": 0.9,
    "label": "rep"
  },
  {
    "t": 1791040272000,
    "source": "simulator",
    "hr": 78.6,
    "rr": [
      779.4
    ],
    "quality": 0.9,
    "label": "rep"
  },
  {
    "t": 1791040273000,
    "source": "simulator",
    "hr": 78.5,
    "rr": [
      748.1
    ],
    "quality": 0.9,
    "label": "rep"
  },
  {
    "t": 1791040274000,
    "source": "simulator",
    "hr": 78.5,
    "rr": [
      780.7
    ],
    "quality": 0.9,
    "label": "rep"
  },
  {
    "t": 1791040275000,
    "source": "simulator",
    "hr": 78.5,
    "rr": [
      747.8
    ],
    "quality": 0.9,
    "label": "rep"
  },
  {
    "t": 1791040276000,
    "source": "simulator",
    "hr": 78.6,
    "rr": [
      780.1
    ],
    "quality": 0.9,
    "label": "rep"
  },
  {
    "t": 1791040277000,
    "source": "simulator",
    "hr": 78.6,
    "rr": [
      746.5
    ],
    "quality": 0.9,
    "label": "rep"
  },
  {
    "t": 1791040278000,
    "source": "simulator",
    "hr": 78.5,
    "rr": [
      781.4
    ],
    "quality": 0.9,
    "label": "rep"
  },
  {
    "t": 1791040279000,
    "source": "simulator",
    "hr": 78.5,
    "rr": [
      747.1
    ],
    "quality": 0.9,
    "label": "rep"
  },
  {
    "t": 1791040280000,
    "source": "simulator",
    "hr": 78.3,
    "rr": [
      783.6
    ],
    "quality": 0.9,
    "label": "rep"
  },
  {
    "t": 1791040281000,
    "source": "simulator",
    "hr": 78.1,
    "rr": [
      750.7
    ],
    "quality": 0.9,
    "label": "rep"
  },
  {
    "t": 1791040282000,
    "source": "simulator",
    "hr": 77.9,
    "rr": [
      787.9
    ],
    "quality": 0.9,
    "label": "rep"
  },
  {
    "t": 1791040283000,
    "source": "simulator",
    "hr": 77.5,
    "rr": [
      756.4
    ],
    "quality": 0.9,
    "label": "rep"
  },
  {
    "t": 1791040284000,
    "source": "simulator",
    "hr": 77.2,
    "rr": [
      795.2
    ],
    "quality": 0.9,
    "label": "rep"
  },
  {
    "t": 1791040285000,
    "source": "simulator",
    "hr": 76.8,
    "rr": [
      763.1
    ],
    "quality": 0.9,
    "label": "rep"
  },
  {
    "t": 1791040286000,
    "source": "simulator",
    "hr": 76.4,
    "rr": [
      803.6
    ],
    "quality": 0.9,
    "label": "rep"
  },
  {
    "t": 1791040287000,
    "source": "simulator",
    "hr": 76.1,
    "rr": [
      770.0
    ],
    "quality": 0.9,
    "label": "rep"
  },
  {
    "t": 1791040288000,
    "source": "simulator",
    "hr": 75.8,
    "rr": [
      810.2
    ],
    "quality": 0.9,
    "label": "rep"
  },
  {
    "t": 1791040289000,
    "source": "simulator",
    "hr": 75.6,
    "rr": [
      774.9
    ],
    "quality": 0.9,
    "label": "rep"
  },
  {
    "t": 1791040290000,
    "source": "simulator",
    "hr": 75.4,
    "rr": [
      814.7
    ],
    "quality": 0.9,
    "label": "rep"
  },
  {
    "t": 1791040291000,
    "source": "simulator",
    "hr": 75.3,
    "rr": [
      777.7
    ],
    "quality": 0.9,
    "label": "rep"
  },
  {
    "t": 1791040292000,
    "source": "simulator",
    "hr": 75.2,
    "rr": [
      817.1
    ],
    "quality": 0.9,
    "label": "rep"
  },
  {
    "t": 1791040293000,
    "source": "simulator",
    "hr": 75.2,
    "rr": [
      778.5
    ],
    "quality": 0.9,
    "label": "rep"
  },
  {
    "t": 1791040294000,
    "source": "simulator",
    "hr": 75.2,
    "rr": [
      817.5
    ],
    "quality": 0.9,
    "label": "rep"
  },
  {
    "t": 1791040295000,
    "source": "simulator",
    "hr": 75.2,
    "rr": [
      778.1
    ],
    "quality": 0.9,
    "label": "rep"
  },
  {
    "t": 1791040296000,
    "source": "simulator",
    "hr": 75.2,
    "rr": [
      817.8
    ],
    "quality": 0.9,
    "label": "rep"
  },
  {
    "t": 1791040297000,
    "source": "simulator",
    "hr": 75.2,
    "rr": [
      777.8
    ],
    "quality": 0.9,
    "label": "rep"
  },
  {
    "t": 1791040298000,
    "source": "simulator",
    "hr": 75.1,
    "rr": [
      819.2
    ],
    "quality": 0.9,
    "label": "rep"
  },
  {
    "t": 1791040299000,
    "source": "simulator",
    "hr": 75.0,
    "rr": [
      779.6
    ],
    "quality": 0.9,
    "label": "rep"
  },
  {
    "t": 1791040300000,
    "source": "simulator",
    "hr": 74.8,
    "rr": [
      822.7
    ],
    "quality": 0.9,
    "label": "rep"
  },
  {
    "t": 1791040301000,
    "source": "simulator",
    "hr": 74.5,
    "rr": [
      784.7
    ],
    "quality": 0.9,
    "label": "rep"
  },
  {
    "t": 1791040302000,
    "source": "simulator",
    "hr": 74.2,
    "rr": [
      829.5
    ],
    "quality": 1.0,
    "label": "recovery"
  },
  {
    "t": 1791040303000,
    "source": "simulator",
    "hr": 73.7,
    "rr": [
      793.0
    ],
    "quality": 1.0,
    "label": "recovery"
  },
  {
    "t": 1791040304000,
    "source": "simulator",
    "hr": 73.2,
    "rr": [
      841.0
    ],
    "quality": 1.0,
    "label": "recovery"
  },
  {
    "t": 1791040305000,
    "source": "simulator",
    "hr": 72.7,
    "rr": [
      803.7
    ],
    "quality": 1.0,
    "label": "recovery"
  },
  {
    "t": 1791040306000,
    "source": "simulator",
    "hr": 72.3,
    "rr": [
      851.8
    ],
    "quality": 1.0,
    "label": "recovery"
  },
  {
    "t": 1791040307000,
    "source": "simulator",
    "hr": 71.9,
    "rr": [
      812.4
    ],
    "quality": 1.0,
    "label": "recovery"
  },
  {
    "t": 1791040308000,
    "source": "simulator",
    "hr": 71.6,
    "rr": [
      860.4
    ],
    "quality": 1.0,
    "label": "recovery"
  },
  {
    "t": 1791040309000,
    "source": "simulator",
    "hr": 71.3,
    "rr": [
      818.9
    ],
    "quality": 1.0,
    "label": "recovery"
  },
  {
    "t": 1791040310000,
    "source": "simulator",
    "hr": 71.1,
    "rr": [
      866.8
    ],
    "quality": 1.0,
    "label": "recovery"
  },
  {
    "t": 1791040311000,
    "source": "simulator",
    "hr": 70.9,
    "rr": [
      823.1
    ],
    "quality": 1.0,
    "label": "recovery"
  },
  {
    "t": 1791040312000,
    "source": "simulator",
    "hr": 70.8,
    "rr": [
      870.9
    ],
    "quality": 1.0,
    "label": "recovery"
  },
  {
    "t": 1791040313000,
    "source": "simulator",
    "hr": 70.7,
    "rr": [
      825.0
    ],
    "quality": 1.0,
    "label": "recovery"
  },
  {
    "t": 1791040314000,
    "source": "simulator",
    "hr": 70.6,
    "rr": [
      873.8
    ],
    "quality": 1.0,
    "label": "recovery"
  },
  {
    "t": 1791040315000,
    "source": "simulator",
    "hr": 70.5,
    "rr": [
      826.9
    ],
    "quality": 1.0,
    "label": "recovery"
  },
  {
    "t": 1791040316000,
    "source": "simulator",
    "hr": 70.4,
    "rr": [
      876.7
    ],
    "quality": 1.0,
    "label": "recovery"
  },
  {
    "t": 1791040317000,
    "source": "simulator",
    "hr": 70.2,
    "rr": [
      830.0
    ],
    "quality": 1.0,
    "label": "recovery"
  },
  {
    "t": 1791040318000,
    "source": "simulator",
    "hr": 69.9,
    "rr": [
      883.3
    ],
    "quality": 1.0,
    "label": "recovery"
  },
  {
    "t": 1791040319000,
    "source": "simulator",
    "hr": 69.6,
    "rr": [
      836.9
    ],
    "quality": 1.0,
    "label": "recovery"
  },
  {
    "t": 1791040320000,
    "source": "simulator",
    "hr": 69.2,
    "rr": [
      892.5
    ],
    "quality": 1.0,
    "label": "recovery"
  },
  {
    "t": 1791040321000,
    "source": "simulator",
    "hr": 68.8,
    "rr": [
      846.4
    ],
    "quality": 1.0,
    "label": "recovery"
  },
  {
    "t": 1791040322000,
    "source": "simulator",
    "hr": 68.3,
    "rr": [
      904.4
    ],
    "quality": 1.0,
    "label": "recovery"
  },
  {
    "t": 1791040323000,
    "source": "simulator",
    "hr": 68.1,
    "rr": [
      855.1
    ],
    "quality": 1.0,
    "label": "recovery"
  },
  {
    "t": 1791040324000,
    "source": "simulator",
    "hr": 67.9,
    "rr": [
      909.6
    ],
    "quality": 1.0,
    "label": "recovery"
  },
  {
    "t": 1791040325000,
    "source": "simulator",
    "hr": 67.8,
    "rr": [
      859.0
    ],
    "quality": 1.0,
    "label": "recovery"
  },
  {
    "t": 1791040326000,
    "source": "simulator",
    "hr": 67.7,
    "rr": [
      912.2
    ],
    "quality": 1.0,
    "label": "recovery"
  },
  {
    "t": 1791040327000,
    "source": "simulator",
    "hr": 67.6,
    "rr": [
      861.6
    ],
    "quality": 1.0,
    "label": "recovery"
  },
  {
    "t": 1791040328000,
    "source": "simulator",
    "hr": 67.6,
    "rr": [
      913.5
    ],
    "quality": 1.0,
    "label": "recovery"
  },
  {
    "t": 1791040329000,
    "source": "simulator",
    "hr": 67.7,
    "rr": [
      860.3
    ],
    "quality": 1.0,
    "label": "recovery"
  },
  {
    "t": 1791040330000,
    "source": "simulator",
    "hr": 67.8,
    "rr": [
      910.9
    ],
    "quality": 1.0,
    "label": "recovery"
  },
  {
    "t": 1791040331000,
    "source": "simulator",
    "hr": 68.0,
    "rr": [
      856.4
    ],
    "quality": 1.0,
    "label": "recovery"
  },
  {
    "t": 1791040332000,
    "source": "simulator",
    "hr": 68.2,
    "rr": [
      905.7
    ],
    "quality": 1.0,
    "label": "recovery"
  },
  {
    "t": 1791040333000,
    "source": "simulator",
    "hr": 68.4,
    "rr": [
      851.2
    ],
    "quality": 1.0,
    "label": "recovery"
  },
  {
    "t": 1791040334000,
    "source": "simulator",
    "hr": 68.6,
    "rr": [
      900.6
    ],
    "quality": 1.0,
    "label": "recovery"
  },
  {
    "t": 1791040335000,
    "source": "simulator",
    "hr": 68.7,
    "rr": [
      847.4
    ],
    "quality": 1.0,
    "label": "recovery"
  },
  {
    "t": 1791040336000,
    "source": "simulator",
    "hr": 68.8,
    "rr": [
      898.1
    ],
    "quality": 1.0,
    "label": "recovery"
  },
  {
    "t": 1791040337000,
    "source": "simulator",
    "hr": 68.8,
    "rr": [
      846.1
    ],
    "quality": 1.0,
    "label": "recovery"
  },
  {
    "t": 1791040338000,
    "source": "simulator",
    "hr": 68.7,
    "rr": [
      899.3
    ],
    "quality": 1.0,
    "label": "recovery"
  },
  {
    "t": 1791040339000,
    "source": "simulator",
    "hr": 68.6,
    "rr": [
      848.7
    ],
    "quality": 1.0,
    "label": "recovery"
  }
];

/** fixtures/detection.drift.json */
export const detectionDrift: DetectionEvent = {
  "schemaVersion": 1,
  "id": "det_demo_001",
  "t": 1791040256000,
  "kind": "drift",
  "stateId": "calm-before-pitch",
  "confidence": 0.83,
  "window": {
    "seconds": 20,
    "hrMean": 77.9,
    "rmssd": 33.8,
    "hrDelta": 9.7,
    "rmssdDelta": -18.1,
    "z": 3.2,
    "position": 0.86
  },
  "gate": {
    "consecutiveWindows": 3,
    "required": 3,
    "refractorySeconds": 60,
    "sham": false
  },
  "calibrationMode": "contrast"
};

/** fixtures/detection.manual.json */
export const detectionManual: DetectionEvent = {
  "schemaVersion": 1,
  "id": "det_demo_manual_001",
  "t": 1791040500000,
  "kind": "manual",
  "stateId": "calm-before-pitch",
  "confidence": 1.0,
  "window": null,
  "gate": {
    "consecutiveWindows": 0,
    "required": 3,
    "refractorySeconds": 60,
    "sham": false
  },
  "calibrationMode": "contrast"
};

/** fixtures/rep-session.full.json */
export const repSessionFull: RepSession = {
  "schemaVersion": 1,
  "id": "rep_demo_003",
  "profileId": "profile_demo_ada",
  "stateId": "calm-before-pitch",
  "repIndex": 3,
  "kind": "full",
  "phase": null,
  "trigger": {
    "kind": "detection",
    "detectionId": "det_demo_001"
  },
  "arm": "cue",
  "startedAt": "2026-10-03T15:10:56Z",
  "endedAt": "2026-10-03T15:11:36Z",
  "steps": [
    {
      "kind": "rate",
      "plannedMs": null,
      "startedAt": "2026-10-03T15:10:56Z",
      "endedAt": "2026-10-03T15:11:00Z",
      "delivered": true
    },
    {
      "kind": "strategy-step",
      "stepIndex": 0,
      "driversSpoken": [
        2,
        3
      ],
      "plannedMs": 8000,
      "startedAt": "2026-10-03T15:11:00Z",
      "endedAt": "2026-10-03T15:11:08Z",
      "delivered": true
    },
    {
      "kind": "strategy-step",
      "stepIndex": 1,
      "driversSpoken": [
        5
      ],
      "plannedMs": 6000,
      "startedAt": "2026-10-03T15:11:08Z",
      "endedAt": "2026-10-03T15:11:14Z",
      "delivered": true
    },
    {
      "kind": "strategy-step",
      "stepIndex": 2,
      "driversSpoken": [],
      "plannedMs": 7000,
      "startedAt": "2026-10-03T15:11:14Z",
      "endedAt": "2026-10-03T15:11:21Z",
      "delivered": true
    },
    {
      "kind": "leverage",
      "plannedMs": 4000,
      "startedAt": "2026-10-03T15:11:21Z",
      "endedAt": "2026-10-03T15:11:25Z",
      "delivered": true
    },
    {
      "kind": "anchor-peak",
      "stepIndex": 0,
      "driversSpoken": [
        2,
        3
      ],
      "plannedMs": 7000,
      "startedAt": "2026-10-03T15:11:25Z",
      "endedAt": "2026-10-03T15:11:32Z",
      "delivered": true
    },
    {
      "kind": "rate",
      "plannedMs": null,
      "startedAt": "2026-10-03T15:11:32Z",
      "endedAt": "2026-10-03T15:11:36Z",
      "delivered": true
    }
  ],
  "intensityBefore": 4,
  "intensityAfter": 8,
  "recoverySeconds": 41,
  "recoveryCensored": false,
  "anchorPaired": true,
  "signalSource": "simulator",
  "scriptHash": "sha256:5f1c0a9e7d3b2a41",
  "endedBy": "completed"
};

/** fixtures/rep-session.sham.json */
export const repSessionSham: RepSession = {
  "schemaVersion": 1,
  "id": "rep_demo_004",
  "profileId": "profile_demo_ada",
  "stateId": "calm-before-pitch",
  "repIndex": 4,
  "kind": "full",
  "phase": null,
  "trigger": {
    "kind": "detection",
    "detectionId": "det_demo_002"
  },
  "arm": "sham",
  "startedAt": "2026-10-03T18:10:56Z",
  "endedAt": "2026-10-03T18:11:04Z",
  "steps": [
    {
      "kind": "rate",
      "plannedMs": null,
      "startedAt": "2026-10-03T18:10:56Z",
      "endedAt": "2026-10-03T18:11:00Z",
      "delivered": true
    },
    {
      "kind": "rate",
      "plannedMs": null,
      "startedAt": "2026-10-03T18:11:00Z",
      "endedAt": "2026-10-03T18:11:04Z",
      "delivered": true
    }
  ],
  "intensityBefore": 4,
  "intensityAfter": 5,
  "recoverySeconds": 80,
  "recoveryCensored": false,
  "anchorPaired": false,
  "signalSource": "simulator",
  "scriptHash": "sha256:5f1c0a9e7d3b2a41",
  "endedBy": "completed"
};

/** fixtures/rep-session.anchor-only.json */
export const repSessionAnchorOnly: RepSession = {
  "schemaVersion": 1,
  "id": "rep_demo_009",
  "profileId": "profile_demo_ada",
  "stateId": "calm-before-pitch",
  "repIndex": 9,
  "kind": "anchor-only",
  "phase": null,
  "trigger": {
    "kind": "practice"
  },
  "arm": "cue",
  "startedAt": "2026-10-04T09:10:56Z",
  "endedAt": "2026-10-04T09:11:10Z",
  "steps": [
    {
      "kind": "rate",
      "plannedMs": null,
      "startedAt": "2026-10-04T09:10:56Z",
      "endedAt": "2026-10-04T09:11:00Z",
      "delivered": true
    },
    {
      "kind": "anchor",
      "stepIndex": 0,
      "plannedMs": 6000,
      "startedAt": "2026-10-04T09:11:00Z",
      "endedAt": "2026-10-04T09:11:06Z",
      "delivered": true
    },
    {
      "kind": "rate",
      "plannedMs": null,
      "startedAt": "2026-10-04T09:11:06Z",
      "endedAt": "2026-10-04T09:11:10Z",
      "delivered": true
    }
  ],
  "intensityBefore": 4,
  "intensityAfter": 7,
  "recoverySeconds": null,
  "recoveryCensored": false,
  "anchorPaired": false,
  "signalSource": "simulator",
  "scriptHash": "sha256:a03be1d47c9f6e22",
  "endedBy": "completed"
};

/** fixtures/rep-log.demo.json */
export const repLogDemo: RepSession[] = [
  {
    "schemaVersion": 1,
    "id": "rep_demo_000",
    "profileId": "profile_demo_ada",
    "stateId": "calm-before-pitch",
    "repIndex": 0,
    "kind": "full",
    "phase": "recode",
    "trigger": {
      "kind": "onboarding"
    },
    "arm": "cue",
    "startedAt": "2026-10-03T15:02:00Z",
    "endedAt": "2026-10-03T15:02:40Z",
    "steps": [
      {
        "kind": "rate",
        "plannedMs": null,
        "startedAt": "2026-10-03T15:02:00Z",
        "endedAt": "2026-10-03T15:02:04Z",
        "delivered": true
      },
      {
        "kind": "strategy-step",
        "stepIndex": 0,
        "driversSpoken": [
          2,
          3
        ],
        "plannedMs": 8000,
        "startedAt": "2026-10-03T15:02:04Z",
        "endedAt": "2026-10-03T15:02:12Z",
        "delivered": true
      },
      {
        "kind": "strategy-step",
        "stepIndex": 1,
        "driversSpoken": [
          5
        ],
        "plannedMs": 6000,
        "startedAt": "2026-10-03T15:02:12Z",
        "endedAt": "2026-10-03T15:02:18Z",
        "delivered": true
      },
      {
        "kind": "strategy-step",
        "stepIndex": 2,
        "driversSpoken": [],
        "plannedMs": 7000,
        "startedAt": "2026-10-03T15:02:18Z",
        "endedAt": "2026-10-03T15:02:25Z",
        "delivered": true
      },
      {
        "kind": "leverage",
        "plannedMs": 4000,
        "startedAt": "2026-10-03T15:02:25Z",
        "endedAt": "2026-10-03T15:02:29Z",
        "delivered": true
      },
      {
        "kind": "anchor-peak",
        "stepIndex": 0,
        "driversSpoken": [
          2,
          3
        ],
        "plannedMs": 7000,
        "startedAt": "2026-10-03T15:02:29Z",
        "endedAt": "2026-10-03T15:02:36Z",
        "delivered": true
      },
      {
        "kind": "rate",
        "plannedMs": null,
        "startedAt": "2026-10-03T15:02:36Z",
        "endedAt": "2026-10-03T15:02:40Z",
        "delivered": true
      }
    ],
    "intensityBefore": 3,
    "intensityAfter": 6,
    "recoverySeconds": null,
    "recoveryCensored": false,
    "anchorPaired": false,
    "signalSource": "none",
    "scriptHash": "sha256:5f1c0a9e7d3b2a41",
    "endedBy": "completed"
  },
  {
    "schemaVersion": 1,
    "id": "rep_demo_001",
    "profileId": "profile_demo_ada",
    "stateId": "calm-before-pitch",
    "repIndex": 1,
    "kind": "full",
    "phase": "test",
    "trigger": {
      "kind": "onboarding"
    },
    "arm": "cue",
    "startedAt": "2026-10-03T15:03:00Z",
    "endedAt": "2026-10-03T15:03:40Z",
    "steps": [
      {
        "kind": "rate",
        "plannedMs": null,
        "startedAt": "2026-10-03T15:03:00Z",
        "endedAt": "2026-10-03T15:03:04Z",
        "delivered": true
      },
      {
        "kind": "strategy-step",
        "stepIndex": 0,
        "driversSpoken": [
          2,
          3
        ],
        "plannedMs": 8000,
        "startedAt": "2026-10-03T15:03:04Z",
        "endedAt": "2026-10-03T15:03:12Z",
        "delivered": true
      },
      {
        "kind": "strategy-step",
        "stepIndex": 1,
        "driversSpoken": [
          5
        ],
        "plannedMs": 6000,
        "startedAt": "2026-10-03T15:03:12Z",
        "endedAt": "2026-10-03T15:03:18Z",
        "delivered": true
      },
      {
        "kind": "strategy-step",
        "stepIndex": 2,
        "driversSpoken": [],
        "plannedMs": 7000,
        "startedAt": "2026-10-03T15:03:18Z",
        "endedAt": "2026-10-03T15:03:25Z",
        "delivered": true
      },
      {
        "kind": "leverage",
        "plannedMs": 4000,
        "startedAt": "2026-10-03T15:03:25Z",
        "endedAt": "2026-10-03T15:03:29Z",
        "delivered": true
      },
      {
        "kind": "anchor-peak",
        "stepIndex": 0,
        "driversSpoken": [
          2,
          3
        ],
        "plannedMs": 7000,
        "startedAt": "2026-10-03T15:03:29Z",
        "endedAt": "2026-10-03T15:03:36Z",
        "delivered": true
      },
      {
        "kind": "rate",
        "plannedMs": null,
        "startedAt": "2026-10-03T15:03:36Z",
        "endedAt": "2026-10-03T15:03:40Z",
        "delivered": true
      }
    ],
    "intensityBefore": 3,
    "intensityAfter": 7,
    "recoverySeconds": null,
    "recoveryCensored": false,
    "anchorPaired": false,
    "signalSource": "none",
    "scriptHash": "sha256:5f1c0a9e7d3b2a41",
    "endedBy": "completed"
  },
  {
    "schemaVersion": 1,
    "id": "rep_demo_002",
    "profileId": "profile_demo_ada",
    "stateId": "calm-before-pitch",
    "repIndex": 2,
    "kind": "full",
    "phase": "future-pace",
    "trigger": {
      "kind": "onboarding"
    },
    "arm": "cue",
    "startedAt": "2026-10-03T15:04:00Z",
    "endedAt": "2026-10-03T15:04:40Z",
    "steps": [
      {
        "kind": "rate",
        "plannedMs": null,
        "startedAt": "2026-10-03T15:04:00Z",
        "endedAt": "2026-10-03T15:04:04Z",
        "delivered": true
      },
      {
        "kind": "strategy-step",
        "stepIndex": 0,
        "driversSpoken": [
          2,
          3
        ],
        "plannedMs": 8000,
        "startedAt": "2026-10-03T15:04:04Z",
        "endedAt": "2026-10-03T15:04:12Z",
        "delivered": true
      },
      {
        "kind": "strategy-step",
        "stepIndex": 1,
        "driversSpoken": [
          5
        ],
        "plannedMs": 6000,
        "startedAt": "2026-10-03T15:04:12Z",
        "endedAt": "2026-10-03T15:04:18Z",
        "delivered": true
      },
      {
        "kind": "strategy-step",
        "stepIndex": 2,
        "driversSpoken": [],
        "plannedMs": 7000,
        "startedAt": "2026-10-03T15:04:18Z",
        "endedAt": "2026-10-03T15:04:25Z",
        "delivered": true
      },
      {
        "kind": "leverage",
        "plannedMs": 4000,
        "startedAt": "2026-10-03T15:04:25Z",
        "endedAt": "2026-10-03T15:04:29Z",
        "delivered": true
      },
      {
        "kind": "anchor-peak",
        "stepIndex": 0,
        "driversSpoken": [
          2,
          3
        ],
        "plannedMs": 7000,
        "startedAt": "2026-10-03T15:04:29Z",
        "endedAt": "2026-10-03T15:04:36Z",
        "delivered": true
      },
      {
        "kind": "rate",
        "plannedMs": null,
        "startedAt": "2026-10-03T15:04:36Z",
        "endedAt": "2026-10-03T15:04:40Z",
        "delivered": true
      }
    ],
    "intensityBefore": 5,
    "intensityAfter": 8,
    "recoverySeconds": null,
    "recoveryCensored": false,
    "anchorPaired": true,
    "signalSource": "none",
    "scriptHash": "sha256:5f1c0a9e7d3b2a41",
    "endedBy": "completed"
  },
  {
    "schemaVersion": 1,
    "id": "rep_demo_003",
    "profileId": "profile_demo_ada",
    "stateId": "calm-before-pitch",
    "repIndex": 3,
    "kind": "full",
    "phase": null,
    "trigger": {
      "kind": "detection",
      "detectionId": "det_demo_001"
    },
    "arm": "cue",
    "startedAt": "2026-10-03T15:10:56Z",
    "endedAt": "2026-10-03T15:11:36Z",
    "steps": [
      {
        "kind": "rate",
        "plannedMs": null,
        "startedAt": "2026-10-03T15:10:56Z",
        "endedAt": "2026-10-03T15:11:00Z",
        "delivered": true
      },
      {
        "kind": "strategy-step",
        "stepIndex": 0,
        "driversSpoken": [
          2,
          3
        ],
        "plannedMs": 8000,
        "startedAt": "2026-10-03T15:11:00Z",
        "endedAt": "2026-10-03T15:11:08Z",
        "delivered": true
      },
      {
        "kind": "strategy-step",
        "stepIndex": 1,
        "driversSpoken": [
          5
        ],
        "plannedMs": 6000,
        "startedAt": "2026-10-03T15:11:08Z",
        "endedAt": "2026-10-03T15:11:14Z",
        "delivered": true
      },
      {
        "kind": "strategy-step",
        "stepIndex": 2,
        "driversSpoken": [],
        "plannedMs": 7000,
        "startedAt": "2026-10-03T15:11:14Z",
        "endedAt": "2026-10-03T15:11:21Z",
        "delivered": true
      },
      {
        "kind": "leverage",
        "plannedMs": 4000,
        "startedAt": "2026-10-03T15:11:21Z",
        "endedAt": "2026-10-03T15:11:25Z",
        "delivered": true
      },
      {
        "kind": "anchor-peak",
        "stepIndex": 0,
        "driversSpoken": [
          2,
          3
        ],
        "plannedMs": 7000,
        "startedAt": "2026-10-03T15:11:25Z",
        "endedAt": "2026-10-03T15:11:32Z",
        "delivered": true
      },
      {
        "kind": "rate",
        "plannedMs": null,
        "startedAt": "2026-10-03T15:11:32Z",
        "endedAt": "2026-10-03T15:11:36Z",
        "delivered": true
      }
    ],
    "intensityBefore": 4,
    "intensityAfter": 8,
    "recoverySeconds": 41,
    "recoveryCensored": false,
    "anchorPaired": true,
    "signalSource": "simulator",
    "scriptHash": "sha256:5f1c0a9e7d3b2a41",
    "endedBy": "completed"
  },
  {
    "schemaVersion": 1,
    "id": "rep_demo_004",
    "profileId": "profile_demo_ada",
    "stateId": "calm-before-pitch",
    "repIndex": 4,
    "kind": "full",
    "phase": null,
    "trigger": {
      "kind": "detection",
      "detectionId": "det_demo_002"
    },
    "arm": "sham",
    "startedAt": "2026-10-03T18:10:56Z",
    "endedAt": "2026-10-03T18:11:04Z",
    "steps": [
      {
        "kind": "rate",
        "plannedMs": null,
        "startedAt": "2026-10-03T18:10:56Z",
        "endedAt": "2026-10-03T18:11:00Z",
        "delivered": true
      },
      {
        "kind": "rate",
        "plannedMs": null,
        "startedAt": "2026-10-03T18:11:00Z",
        "endedAt": "2026-10-03T18:11:04Z",
        "delivered": true
      }
    ],
    "intensityBefore": 4,
    "intensityAfter": 5,
    "recoverySeconds": 80,
    "recoveryCensored": false,
    "anchorPaired": false,
    "signalSource": "simulator",
    "scriptHash": "sha256:5f1c0a9e7d3b2a41",
    "endedBy": "completed"
  },
  {
    "schemaVersion": 1,
    "id": "rep_demo_005",
    "profileId": "profile_demo_ada",
    "stateId": "calm-before-pitch",
    "repIndex": 5,
    "kind": "full",
    "phase": null,
    "trigger": {
      "kind": "manual",
      "detectionId": "det_demo_manual_001"
    },
    "arm": "cue",
    "startedAt": "2026-10-03T21:10:56Z",
    "endedAt": "2026-10-03T21:11:36Z",
    "steps": [
      {
        "kind": "rate",
        "plannedMs": null,
        "startedAt": "2026-10-03T21:10:56Z",
        "endedAt": "2026-10-03T21:11:00Z",
        "delivered": true
      },
      {
        "kind": "strategy-step",
        "stepIndex": 0,
        "driversSpoken": [
          2,
          3
        ],
        "plannedMs": 8000,
        "startedAt": "2026-10-03T21:11:00Z",
        "endedAt": "2026-10-03T21:11:08Z",
        "delivered": true
      },
      {
        "kind": "strategy-step",
        "stepIndex": 1,
        "driversSpoken": [
          5
        ],
        "plannedMs": 6000,
        "startedAt": "2026-10-03T21:11:08Z",
        "endedAt": "2026-10-03T21:11:14Z",
        "delivered": true
      },
      {
        "kind": "strategy-step",
        "stepIndex": 2,
        "driversSpoken": [],
        "plannedMs": 7000,
        "startedAt": "2026-10-03T21:11:14Z",
        "endedAt": "2026-10-03T21:11:21Z",
        "delivered": true
      },
      {
        "kind": "leverage",
        "plannedMs": 4000,
        "startedAt": "2026-10-03T21:11:21Z",
        "endedAt": "2026-10-03T21:11:25Z",
        "delivered": true
      },
      {
        "kind": "anchor-peak",
        "stepIndex": 0,
        "driversSpoken": [
          2,
          3
        ],
        "plannedMs": 7000,
        "startedAt": "2026-10-03T21:11:25Z",
        "endedAt": "2026-10-03T21:11:32Z",
        "delivered": true
      },
      {
        "kind": "rate",
        "plannedMs": null,
        "startedAt": "2026-10-03T21:11:32Z",
        "endedAt": "2026-10-03T21:11:36Z",
        "delivered": true
      }
    ],
    "intensityBefore": 3,
    "intensityAfter": 7,
    "recoverySeconds": 38,
    "recoveryCensored": false,
    "anchorPaired": true,
    "signalSource": "simulator",
    "scriptHash": "sha256:5f1c0a9e7d3b2a41",
    "endedBy": "completed"
  },
  {
    "schemaVersion": 1,
    "id": "rep_demo_006",
    "profileId": "profile_demo_ada",
    "stateId": "calm-before-pitch",
    "repIndex": 6,
    "kind": "full",
    "phase": null,
    "trigger": {
      "kind": "detection",
      "detectionId": "det_demo_003"
    },
    "arm": "cue",
    "startedAt": "2026-10-04T00:10:56Z",
    "endedAt": "2026-10-04T00:11:36Z",
    "steps": [
      {
        "kind": "rate",
        "plannedMs": null,
        "startedAt": "2026-10-04T00:10:56Z",
        "endedAt": "2026-10-04T00:11:00Z",
        "delivered": true
      },
      {
        "kind": "strategy-step",
        "stepIndex": 0,
        "driversSpoken": [
          2,
          3
        ],
        "plannedMs": 8000,
        "startedAt": "2026-10-04T00:11:00Z",
        "endedAt": "2026-10-04T00:11:08Z",
        "delivered": true
      },
      {
        "kind": "strategy-step",
        "stepIndex": 1,
        "driversSpoken": [
          5
        ],
        "plannedMs": 6000,
        "startedAt": "2026-10-04T00:11:08Z",
        "endedAt": "2026-10-04T00:11:14Z",
        "delivered": true
      },
      {
        "kind": "strategy-step",
        "stepIndex": 2,
        "driversSpoken": [],
        "plannedMs": 7000,
        "startedAt": "2026-10-04T00:11:14Z",
        "endedAt": "2026-10-04T00:11:21Z",
        "delivered": true
      },
      {
        "kind": "leverage",
        "plannedMs": 4000,
        "startedAt": "2026-10-04T00:11:21Z",
        "endedAt": "2026-10-04T00:11:25Z",
        "delivered": true
      },
      {
        "kind": "anchor-peak",
        "stepIndex": 0,
        "driversSpoken": [
          2,
          3
        ],
        "plannedMs": 7000,
        "startedAt": "2026-10-04T00:11:25Z",
        "endedAt": "2026-10-04T00:11:32Z",
        "delivered": true
      },
      {
        "kind": "rate",
        "plannedMs": null,
        "startedAt": "2026-10-04T00:11:32Z",
        "endedAt": "2026-10-04T00:11:36Z",
        "delivered": true
      }
    ],
    "intensityBefore": 4,
    "intensityAfter": 8,
    "recoverySeconds": 35,
    "recoveryCensored": false,
    "anchorPaired": true,
    "signalSource": "simulator",
    "scriptHash": "sha256:5f1c0a9e7d3b2a41",
    "endedBy": "completed"
  },
  {
    "schemaVersion": 1,
    "id": "rep_demo_007",
    "profileId": "profile_demo_ada",
    "stateId": "calm-before-pitch",
    "repIndex": 7,
    "kind": "full",
    "phase": null,
    "trigger": {
      "kind": "detection",
      "detectionId": "det_demo_004"
    },
    "arm": "sham",
    "startedAt": "2026-10-04T03:10:56Z",
    "endedAt": "2026-10-04T03:11:04Z",
    "steps": [
      {
        "kind": "rate",
        "plannedMs": null,
        "startedAt": "2026-10-04T03:10:56Z",
        "endedAt": "2026-10-04T03:11:00Z",
        "delivered": true
      },
      {
        "kind": "rate",
        "plannedMs": null,
        "startedAt": "2026-10-04T03:11:00Z",
        "endedAt": "2026-10-04T03:11:04Z",
        "delivered": true
      }
    ],
    "intensityBefore": 4,
    "intensityAfter": 4,
    "recoverySeconds": null,
    "recoveryCensored": true,
    "anchorPaired": false,
    "signalSource": "simulator",
    "scriptHash": "sha256:5f1c0a9e7d3b2a41",
    "endedBy": "completed"
  },
  {
    "schemaVersion": 1,
    "id": "rep_demo_008",
    "profileId": "profile_demo_ada",
    "stateId": "calm-before-pitch",
    "repIndex": 8,
    "kind": "full",
    "phase": null,
    "trigger": {
      "kind": "practice"
    },
    "arm": "cue",
    "startedAt": "2026-10-04T06:10:56Z",
    "endedAt": "2026-10-04T06:11:36Z",
    "steps": [
      {
        "kind": "rate",
        "plannedMs": null,
        "startedAt": "2026-10-04T06:10:56Z",
        "endedAt": "2026-10-04T06:11:00Z",
        "delivered": true
      },
      {
        "kind": "strategy-step",
        "stepIndex": 0,
        "driversSpoken": [
          2,
          3
        ],
        "plannedMs": 8000,
        "startedAt": "2026-10-04T06:11:00Z",
        "endedAt": "2026-10-04T06:11:08Z",
        "delivered": true
      },
      {
        "kind": "strategy-step",
        "stepIndex": 1,
        "driversSpoken": [
          5
        ],
        "plannedMs": 6000,
        "startedAt": "2026-10-04T06:11:08Z",
        "endedAt": "2026-10-04T06:11:14Z",
        "delivered": true
      },
      {
        "kind": "strategy-step",
        "stepIndex": 2,
        "driversSpoken": [],
        "plannedMs": 7000,
        "startedAt": "2026-10-04T06:11:14Z",
        "endedAt": "2026-10-04T06:11:21Z",
        "delivered": true
      },
      {
        "kind": "leverage",
        "plannedMs": 4000,
        "startedAt": "2026-10-04T06:11:21Z",
        "endedAt": "2026-10-04T06:11:25Z",
        "delivered": true
      },
      {
        "kind": "anchor-peak",
        "stepIndex": 0,
        "driversSpoken": [
          2,
          3
        ],
        "plannedMs": 7000,
        "startedAt": "2026-10-04T06:11:25Z",
        "endedAt": "2026-10-04T06:11:32Z",
        "delivered": true
      },
      {
        "kind": "rate",
        "plannedMs": null,
        "startedAt": "2026-10-04T06:11:32Z",
        "endedAt": "2026-10-04T06:11:36Z",
        "delivered": true
      }
    ],
    "intensityBefore": 5,
    "intensityAfter": 8,
    "recoverySeconds": null,
    "recoveryCensored": false,
    "anchorPaired": true,
    "signalSource": "simulator",
    "scriptHash": "sha256:5f1c0a9e7d3b2a41",
    "endedBy": "completed"
  },
  {
    "schemaVersion": 1,
    "id": "rep_demo_009",
    "profileId": "profile_demo_ada",
    "stateId": "calm-before-pitch",
    "repIndex": 9,
    "kind": "anchor-only",
    "phase": null,
    "trigger": {
      "kind": "practice"
    },
    "arm": "cue",
    "startedAt": "2026-10-04T09:10:56Z",
    "endedAt": "2026-10-04T09:11:10Z",
    "steps": [
      {
        "kind": "rate",
        "plannedMs": null,
        "startedAt": "2026-10-04T09:10:56Z",
        "endedAt": "2026-10-04T09:11:00Z",
        "delivered": true
      },
      {
        "kind": "anchor",
        "stepIndex": 0,
        "plannedMs": 6000,
        "startedAt": "2026-10-04T09:11:00Z",
        "endedAt": "2026-10-04T09:11:06Z",
        "delivered": true
      },
      {
        "kind": "rate",
        "plannedMs": null,
        "startedAt": "2026-10-04T09:11:06Z",
        "endedAt": "2026-10-04T09:11:10Z",
        "delivered": true
      }
    ],
    "intensityBefore": 4,
    "intensityAfter": 7,
    "recoverySeconds": null,
    "recoveryCensored": false,
    "anchorPaired": false,
    "signalSource": "simulator",
    "scriptHash": "sha256:a03be1d47c9f6e22",
    "endedBy": "completed"
  },
  {
    "schemaVersion": 1,
    "id": "rep_demo_010",
    "profileId": "profile_demo_ada",
    "stateId": "calm-before-pitch",
    "repIndex": 10,
    "kind": "anchor-only",
    "phase": null,
    "trigger": {
      "kind": "practice"
    },
    "arm": "cue",
    "startedAt": "2026-10-04T12:10:56Z",
    "endedAt": "2026-10-04T12:11:10Z",
    "steps": [
      {
        "kind": "rate",
        "plannedMs": null,
        "startedAt": "2026-10-04T12:10:56Z",
        "endedAt": "2026-10-04T12:11:00Z",
        "delivered": true
      },
      {
        "kind": "anchor",
        "stepIndex": 0,
        "plannedMs": 6000,
        "startedAt": "2026-10-04T12:11:00Z",
        "endedAt": "2026-10-04T12:11:06Z",
        "delivered": true
      },
      {
        "kind": "rate",
        "plannedMs": null,
        "startedAt": "2026-10-04T12:11:06Z",
        "endedAt": "2026-10-04T12:11:10Z",
        "delivered": true
      }
    ],
    "intensityBefore": 4,
    "intensityAfter": 8,
    "recoverySeconds": null,
    "recoveryCensored": false,
    "anchorPaired": false,
    "signalSource": "simulator",
    "scriptHash": "sha256:a03be1d47c9f6e22",
    "endedBy": "completed"
  }
];

/** fixtures/onboarding.events.demo.json */
export const onboardingEventsDemo: OnboardingEvent[] = [
  {
    "type": "guideTurn",
    "text": "What state do you want to be able to get back to? Say it in your own words.",
    "section": "1.1",
    "t": 1791039600000
  },
  {
    "type": "userTurn",
    "text": "Calm before a pitch. Like the room is already mine and there's no rush.",
    "final": true,
    "via": "script",
    "t": 1791039603000
  },
  {
    "type": "stateNamed",
    "stateId": "calm-before-pitch",
    "label": "calm before a pitch",
    "words": "Like the room is already mine and there's no rush",
    "t": 1791039605000
  },
  {
    "type": "guideTurn",
    "text": "Can you remember a specific time you were totally calm before a pitch? Step into it. Tell me when you're there.",
    "section": "1.2",
    "t": 1791039605500
  },
  {
    "type": "userTurn",
    "text": "The Berlin demo. I'm there.",
    "final": true,
    "via": "script",
    "t": 1791039608500
  },
  {
    "type": "guideTurn",
    "text": "What was the very first thing that caused it? Something you saw, heard, or felt?",
    "section": "1.3",
    "t": 1791039610500
  },
  {
    "type": "userTurn",
    "text": "The first face in the room looking up at me.",
    "final": true,
    "via": "script",
    "t": 1791039613500
  },
  {
    "type": "stepCaptured",
    "stateId": "calm-before-pitch",
    "stepIndex": 0,
    "step": {
      "modality": "visual",
      "direction": "external",
      "content": "the first face in the room looking up at me",
      "submodalities": {
        "core": {
          "location": "center",
          "size": "life-size",
          "distance": "close",
          "brightness": "bright",
          "perspective": "associated"
        },
        "extended": {
          "motion": "movie"
        },
        "words": {
          "distance": "right there, like across a table"
        }
      },
      "anchorDetail": {
        "kind": "scene",
        "caption": "The first face looking up",
        "details": [
          "warm window light",
          "a coffee cup on the table"
        ]
      }
    },
    "fullyIn": false,
    "t": 1791039615500
  },
  {
    "type": "submodalityCaptured",
    "stateId": "calm-before-pitch",
    "target": "peak",
    "stepIndex": 0,
    "modality": "visual",
    "attribute": "location",
    "value": "center",
    "t": 1791039616000
  },
  {
    "type": "submodalityCaptured",
    "stateId": "calm-before-pitch",
    "target": "peak",
    "stepIndex": 0,
    "modality": "visual",
    "attribute": "size",
    "value": "life-size",
    "t": 1791039617500
  },
  {
    "type": "submodalityCaptured",
    "stateId": "calm-before-pitch",
    "target": "peak",
    "stepIndex": 0,
    "modality": "visual",
    "attribute": "distance",
    "value": "close",
    "t": 1791039619000
  },
  {
    "type": "submodalityCaptured",
    "stateId": "calm-before-pitch",
    "target": "peak",
    "stepIndex": 0,
    "modality": "visual",
    "attribute": "brightness",
    "value": "bright",
    "t": 1791039620500
  },
  {
    "type": "submodalityCaptured",
    "stateId": "calm-before-pitch",
    "target": "peak",
    "stepIndex": 0,
    "modality": "visual",
    "attribute": "perspective",
    "value": "associated",
    "t": 1791039622000
  },
  {
    "type": "guideTurn",
    "text": "After that, what was the very next thing? A picture, something you said to yourself, or a feeling?",
    "section": "1.4",
    "t": 1791039623500
  },
  {
    "type": "userTurn",
    "text": "I said to myself, here we go, slow.",
    "final": true,
    "via": "script",
    "t": 1791039626500
  },
  {
    "type": "stepCaptured",
    "stateId": "calm-before-pitch",
    "stepIndex": 1,
    "step": {
      "modality": "auditory",
      "direction": "internal",
      "content": "'here we go, slow'",
      "submodalities": {
        "core": {
          "source": "my own voice",
          "volume": "quiet",
          "location": "inside-head"
        },
        "extended": {
          "tempo": "slow"
        }
      }
    },
    "fullyIn": false,
    "t": 1791039628500
  },
  {
    "type": "submodalityCaptured",
    "stateId": "calm-before-pitch",
    "target": "peak",
    "stepIndex": 1,
    "modality": "auditory",
    "attribute": "source",
    "value": "my own voice",
    "t": 1791039629000
  },
  {
    "type": "submodalityCaptured",
    "stateId": "calm-before-pitch",
    "target": "peak",
    "stepIndex": 1,
    "modality": "auditory",
    "attribute": "volume",
    "value": "quiet",
    "t": 1791039630500
  },
  {
    "type": "submodalityCaptured",
    "stateId": "calm-before-pitch",
    "target": "peak",
    "stepIndex": 1,
    "modality": "auditory",
    "attribute": "location",
    "value": "inside-head",
    "t": 1791039632000
  },
  {
    "type": "guideTurn",
    "text": "And the next thing?",
    "section": "1.5",
    "t": 1791039633500
  },
  {
    "type": "userTurn",
    "text": "Warmth spreading through my chest. That's when I'm fully there.",
    "final": true,
    "via": "script",
    "t": 1791039636500
  },
  {
    "type": "stepCaptured",
    "stateId": "calm-before-pitch",
    "stepIndex": 2,
    "step": {
      "modality": "kinesthetic",
      "direction": "internal",
      "content": "warmth spreading through my chest",
      "submodalities": {
        "core": {
          "bodyLocation": "chest",
          "intensity": 8,
          "movement": "moving"
        },
        "extended": {
          "temperature": "warm",
          "direction": "spreading"
        }
      }
    },
    "fullyIn": true,
    "t": 1791039638500
  },
  {
    "type": "submodalityCaptured",
    "stateId": "calm-before-pitch",
    "target": "peak",
    "stepIndex": 2,
    "modality": "kinesthetic",
    "attribute": "bodyLocation",
    "value": "chest",
    "t": 1791039639000
  },
  {
    "type": "submodalityCaptured",
    "stateId": "calm-before-pitch",
    "target": "peak",
    "stepIndex": 2,
    "modality": "kinesthetic",
    "attribute": "intensity",
    "value": 8,
    "t": 1791039640500
  },
  {
    "type": "submodalityCaptured",
    "stateId": "calm-before-pitch",
    "target": "peak",
    "stepIndex": 2,
    "modality": "kinesthetic",
    "attribute": "movement",
    "value": "moving",
    "t": 1791039642000
  },
  {
    "type": "calibrationCaptured",
    "stateId": "calm-before-pitch",
    "summary": {
      "stateId": "calm-before-pitch",
      "phase": "peak",
      "source": "simulator",
      "hr": {
        "mean": 68.2,
        "sd": 2.1
      },
      "lnRmssd": {
        "mean": 3.95,
        "sd": 0.12
      },
      "windows": 5,
      "seconds": 40,
      "quality": "ok",
      "speechExcludedSeconds": 8,
      "recordedAt": "2026-10-03T15:00:40Z",
      "rating": 8
    },
    "t": 1791039643500
  },
  {
    "type": "guideTurn",
    "text": "So first you see the first face looking up, then you say 'here we go, slow', then you feel warmth spreading in your chest. Is that the order?",
    "section": "1.6",
    "t": 1791039644000
  },
  {
    "type": "userTurn",
    "text": "Yes.",
    "final": true,
    "via": "script",
    "t": 1791039647000
  },
  {
    "type": "guideTurn",
    "text": "Which one of these, if I gave it back to you, would bring the state back fastest?",
    "section": "2",
    "t": 1791039649000
  },
  {
    "type": "userTurn",
    "text": "The face looking up.",
    "final": true,
    "via": "script",
    "t": 1791039652000
  },
  {
    "type": "anchorStepMarked",
    "stateId": "calm-before-pitch",
    "stepIndex": 0,
    "t": 1791039654000
  },
  {
    "type": "contrastCaptured",
    "stateId": "calm-before-pitch",
    "label": "stuck on a small email",
    "prefilled": true,
    "t": 1791039654500
  },
  {
    "type": "calibrationCaptured",
    "stateId": "calm-before-pitch",
    "summary": {
      "stateId": "calm-before-pitch",
      "phase": "contrast",
      "source": "simulator",
      "hr": {
        "mean": 79.5,
        "sd": 3.0
      },
      "lnRmssd": {
        "mean": 3.45,
        "sd": 0.15
      },
      "windows": 3,
      "seconds": 24,
      "quality": "ok",
      "speechExcludedSeconds": 4,
      "recordedAt": "2026-10-03T15:01:10Z",
      "rating": 3,
      "separability": {
        "separable": true,
        "hr": 4.36,
        "lnRmssd": 3.68
      }
    },
    "t": 1791039655000
  },
  {
    "type": "driverFound",
    "stateId": "calm-before-pitch",
    "differenceIndex": 2,
    "difference": {
      "stepIndex": 0,
      "modality": "visual",
      "attribute": "distance",
      "peak": "close",
      "contrast": "far",
      "ratingDelta": 3
    },
    "t": 1791039655500
  },
  {
    "type": "driverFound",
    "stateId": "calm-before-pitch",
    "differenceIndex": 3,
    "difference": {
      "stepIndex": 0,
      "modality": "visual",
      "attribute": "brightness",
      "peak": "bright",
      "contrast": "dim",
      "ratingDelta": 2
    },
    "t": 1791039656000
  },
  {
    "type": "driverFound",
    "stateId": "calm-before-pitch",
    "differenceIndex": 5,
    "difference": {
      "stepIndex": 1,
      "modality": "auditory",
      "attribute": "volume",
      "peak": "quiet",
      "contrast": "loud",
      "ratingDelta": 2
    },
    "t": 1791039656500
  },
  {
    "type": "guideTurn",
    "text": "For you, closeness, brightness and a quiet voice seem to matter most. Take the stuck time and give it those: the picture close and bright, the voice quiet.",
    "section": "4.1",
    "t": 1791039657000
  },
  {
    "type": "userTurn",
    "text": "Okay. That's different.",
    "final": true,
    "via": "script",
    "t": 1791039660000
  },
  {
    "type": "guideTurn",
    "text": "Now think of that old situation again. Where are you, 0 to 10?",
    "section": "4.2",
    "t": 1791039662000
  },
  {
    "type": "userTurn",
    "text": "Seven. It was a three.",
    "final": true,
    "via": "script",
    "t": 1791039665000
  },
  {
    "type": "testRated",
    "stateId": "calm-before-pitch",
    "before": 3,
    "after": 7,
    "t": 1791039667000
  },
  {
    "type": "guideTurn",
    "text": "Think of a time coming up when you'll want this. Run the steps there.",
    "section": "4.3",
    "t": 1791039667500
  },
  {
    "type": "userTurn",
    "text": "Thursday's board pitch.",
    "final": true,
    "via": "script",
    "t": 1791039670500
  },
  {
    "type": "guideTurn",
    "text": "First the face, close and bright. Then 'here we go, slow', quietly. Then the warmth in your chest. That's yours.",
    "section": "4.4",
    "t": 1791039672500
  },
  {
    "type": "confirmed",
    "t": 1791039695000,
    "profile": {
      "schemaVersion": 2,
      "profileId": "profile_demo_ada",
      "displayName": "Ada",
      "createdAt": "2026-10-03T15:00:00Z",
      "confirmedAt": "2026-10-03T15:01:35Z",
      "states": [
        {
          "id": "calm-before-pitch",
          "label": "calm before a pitch",
          "words": "Like the room is already mine and there's no rush",
          "memoryCue": "the Berlin demo",
          "leverage": "So I stop rushing the part that matters",
          "strategy": {
            "steps": [
              {
                "modality": "visual",
                "direction": "external",
                "content": "the first face in the room looking up at me",
                "submodalities": {
                  "core": {
                    "location": "center",
                    "size": "life-size",
                    "distance": "close",
                    "brightness": "bright",
                    "perspective": "associated"
                  },
                  "extended": {
                    "motion": "movie"
                  },
                  "words": {
                    "distance": "right there, like across a table"
                  }
                },
                "anchorDetail": {
                  "kind": "scene",
                  "caption": "The first face looking up",
                  "details": [
                    "warm window light",
                    "a coffee cup on the table"
                  ]
                }
              },
              {
                "modality": "auditory",
                "direction": "internal",
                "content": "'here we go, slow'",
                "submodalities": {
                  "core": {
                    "source": "my own voice",
                    "volume": "quiet",
                    "location": "inside-head"
                  },
                  "extended": {
                    "tempo": "slow"
                  }
                }
              },
              {
                "modality": "kinesthetic",
                "direction": "internal",
                "content": "warmth spreading through my chest",
                "submodalities": {
                  "core": {
                    "bodyLocation": "chest",
                    "intensity": 8,
                    "movement": "moving"
                  },
                  "extended": {
                    "temperature": "warm",
                    "direction": "spreading"
                  }
                }
              }
            ],
            "fullyInAt": 2,
            "confirmed": true
          },
          "anchorStep": 0,
          "contrast": {
            "label": "stuck on a small email",
            "submodalities": {
              "visual": {
                "core": {
                  "location": "lower-left",
                  "size": "small",
                  "distance": "far",
                  "brightness": "dim",
                  "perspective": "dissociated"
                }
              },
              "auditory": {
                "core": {
                  "source": "my own voice",
                  "volume": "loud",
                  "location": "inside-head"
                },
                "extended": {
                  "tempo": "fast"
                }
              },
              "kinesthetic": {
                "core": {
                  "bodyLocation": "stomach",
                  "intensity": 3,
                  "movement": "still"
                }
              }
            },
            "prefilled": true
          },
          "differences": [
            {
              "stepIndex": 0,
              "modality": "visual",
              "attribute": "location",
              "peak": "center",
              "contrast": "lower-left",
              "ratingDelta": 1
            },
            {
              "stepIndex": 0,
              "modality": "visual",
              "attribute": "size",
              "peak": "life-size",
              "contrast": "small",
              "ratingDelta": 1
            },
            {
              "stepIndex": 0,
              "modality": "visual",
              "attribute": "distance",
              "peak": "close",
              "contrast": "far",
              "ratingDelta": 3
            },
            {
              "stepIndex": 0,
              "modality": "visual",
              "attribute": "brightness",
              "peak": "bright",
              "contrast": "dim",
              "ratingDelta": 2
            },
            {
              "stepIndex": 0,
              "modality": "visual",
              "attribute": "perspective",
              "peak": "associated",
              "contrast": "dissociated",
              "ratingDelta": 1
            },
            {
              "stepIndex": 1,
              "modality": "auditory",
              "attribute": "volume",
              "peak": "quiet",
              "contrast": "loud",
              "ratingDelta": 2
            },
            {
              "stepIndex": 1,
              "modality": "auditory",
              "attribute": "tempo",
              "peak": "slow",
              "contrast": "fast",
              "ratingDelta": 1
            },
            {
              "stepIndex": 2,
              "modality": "kinesthetic",
              "attribute": "movement",
              "peak": "moving",
              "contrast": "still",
              "ratingDelta": 1
            }
          ],
          "drivers": [
            2,
            3,
            5
          ],
          "recode": {
            "appliedDrivers": [
              2,
              3,
              5
            ]
          },
          "test": {
            "before": 3,
            "after": 7
          },
          "futurePace": {
            "situation": "Thursday's board pitch"
          },
          "calibration": {
            "peak": {
              "stateId": "calm-before-pitch",
              "phase": "peak",
              "source": "simulator",
              "hr": {
                "mean": 68.2,
                "sd": 2.1
              },
              "lnRmssd": {
                "mean": 3.95,
                "sd": 0.12
              },
              "windows": 5,
              "seconds": 40,
              "quality": "ok",
              "speechExcludedSeconds": 8,
              "recordedAt": "2026-10-03T15:00:40Z",
              "rating": 8
            },
            "contrast": {
              "stateId": "calm-before-pitch",
              "phase": "contrast",
              "source": "simulator",
              "hr": {
                "mean": 79.5,
                "sd": 3.0
              },
              "lnRmssd": {
                "mean": 3.45,
                "sd": 0.15
              },
              "windows": 3,
              "seconds": 24,
              "quality": "ok",
              "speechExcludedSeconds": 4,
              "recordedAt": "2026-10-03T15:01:10Z",
              "rating": 3,
              "separability": {
                "separable": true,
                "hr": 4.36,
                "lnRmssd": 3.68
              }
            }
          }
        }
      ]
    }
  }
];

export const fixtures = {
  profileDemo,
  profileThreeStates,
  profileDraft,
  calibrationPeak,
  calibrationContrast,
  framesDrift,
  detectionDrift,
  detectionManual,
  repSessionFull,
  repSessionSham,
  repSessionAnchorOnly,
  repLogDemo,
  onboardingEventsDemo,
};
